project:
  type: book
  output-dir: docs
  resources:
    - multiqc/

lang: es

book:
  title: "Holofishcolour project"
  site-url: "https://dcosimber.github.io/Transcriptomics/"
  sidebar:
    logo: images/holofishcolour_manhattan_logo_2026.png
    logo-alt: "HOLOFISHCOLOUR"
    logo-href: index.html
    search: true
  author:
    - name: Daniel Costas
      orcid: 0000-0003-4384-8469
      email: daniel.costas.imbernon@gmail.com
      affiliations:
        - name: Instituto de Investigaciones Marinas (IIM-CSIC)
          city: Vigo
          state: Spain
          url: www.iim.csic.es
        - name: Aquabiotec Lab
          city: Vigo
          state: Spain
          url: https://acuabiotec.csic.es

  date: last-modified
  chapters:
    - index.qmd
    - chapters/01_intro.qmd
    - chapters/02_exp_design.qmd
    - chapters/02_methods_nfcore.qmd
    - chapters/03_results.qmd
    - chapters/03_qc_multiqc.qmd
    - chapters/04_alignment_quant.qmd
    - chapters/05_differential_expression.qmd

bibliography: references.bib
csl: vancouver-brackets.csl

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    lightbox:
      match: auto
      effect: zoom
      desc-position: bottom
    css: styles.css
    theme:
      light: cosmo
      dark: darkly

editor: visual
