<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Control de calidad integrado con MultiQC – Holofishcolour project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/04_alignment_quant.html" rel="next">
<link href="../chapters/03_results.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7e34ecb6a0e7991f0346b0751d4a7c3f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/03_qc_multiqc.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Control de calidad integrado con MultiQC</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="index.html" class="sidebar-logo-link">
      <img src="../images/holofishcolour_manhattan_logo_2026.png" alt="HOLOFISHCOLOUR" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../images/holofishcolour_manhattan_logo_2026.png" alt="HOLOFISHCOLOUR" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Holofishcolour project</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">HOLOFISHCOLOUR transcriptomics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02_exp_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Diseño experimental</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02_methods_nfcore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Preprocesamiento bioinformático con nf-core/rnaseq</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">RNA Integrity Number (RIN): technical background</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03_qc_multiqc.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Control de calidad integrado con MultiQC</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04_alignment_quant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">04_alignment_quant.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05_differential_expression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Expresión diferencial</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/rna_extraction_protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Protocolo de extracción de ARN con TRIzol y columnas Phase Lock Gel Heavy</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#resumen-ejecutivo-del-qc" id="toc-resumen-ejecutivo-del-qc" class="nav-link active" data-scroll-target="#resumen-ejecutivo-del-qc"><span class="header-section-number">6.1</span> Resumen ejecutivo del QC</a></li>
  <li><a href="#general-statistics" id="toc-general-statistics" class="nav-link" data-scroll-target="#general-statistics"><span class="header-section-number">6.2</span> General statistics</a></li>
  <li><a href="#fastp-filtrado-calidad-y-composición" id="toc-fastp-filtrado-calidad-y-composición" class="nav-link" data-scroll-target="#fastp-filtrado-calidad-y-composición"><span class="header-section-number">6.3</span> fastp: filtrado, calidad y composición</a>
  <ul class="collapse">
  <li><a href="#interpretación-técnica-y-biológica-de-fastp" id="toc-interpretación-técnica-y-biológica-de-fastp" class="nav-link" data-scroll-target="#interpretación-técnica-y-biológica-de-fastp"><span class="header-section-number">6.3.1</span> Interpretación técnica y biológica de fastp</a></li>
  </ul></li>
  <li><a href="#star-alineamiento-contra-el-genoma-de-referencia" id="toc-star-alineamiento-contra-el-genoma-de-referencia" class="nav-link" data-scroll-target="#star-alineamiento-contra-el-genoma-de-referencia"><span class="header-section-number">6.4</span> STAR: alineamiento contra el genoma de referencia</a></li>
  <li><a href="#samtools-métricas-de-bam-alineado" id="toc-samtools-métricas-de-bam-alineado" class="nav-link" data-scroll-target="#samtools-métricas-de-bam-alineado"><span class="header-section-number">6.5</span> Samtools: métricas de BAM alineado</a></li>
  <li><a href="#picard-duplicación-y-complejidad-de-biblioteca" id="toc-picard-duplicación-y-complejidad-de-biblioteca" class="nav-link" data-scroll-target="#picard-duplicación-y-complejidad-de-biblioteca"><span class="header-section-number">6.6</span> Picard: duplicación y complejidad de biblioteca</a></li>
  <li><a href="#salmon-strand-check-orientación-de-la-biblioteca" id="toc-salmon-strand-check-orientación-de-la-biblioteca" class="nav-link" data-scroll-target="#salmon-strand-check-orientación-de-la-biblioteca"><span class="header-section-number">6.7</span> Salmon / strand check: orientación de la biblioteca</a></li>
  <li><a href="#versiones-de-software" id="toc-versiones-de-software" class="nav-link" data-scroll-target="#versiones-de-software"><span class="header-section-number">6.8</span> Versiones de software</a></li>
  <li><a href="#qc-post-alineamiento-recuperado-con---resume" id="toc-qc-post-alineamiento-recuperado-con---resume" class="nav-link" data-scroll-target="#qc-post-alineamiento-recuperado-con---resume"><span class="header-section-number">6.9</span> QC post-alineamiento recuperado con <code>--resume</code></a>
  <ul class="collapse">
  <li><a href="#qualimap-origen-genómico-y-sesgo-de-cobertura" id="toc-qualimap-origen-genómico-y-sesgo-de-cobertura" class="nav-link" data-scroll-target="#qualimap-origen-genómico-y-sesgo-de-cobertura"><span class="header-section-number">6.9.1</span> Qualimap: origen genómico y sesgo de cobertura</a></li>
  <li><a href="#rseqc-coherencia-de-bam-biblioteca-y-anotación" id="toc-rseqc-coherencia-de-bam-biblioteca-y-anotación" class="nav-link" data-scroll-target="#rseqc-coherencia-de-bam-biblioteca-y-anotación"><span class="header-section-number">6.9.2</span> RSeQC: coherencia de BAM, biblioteca y anotación</a></li>
  <li><a href="#dupradar-duplicación-dependiente-de-expresión" id="toc-dupradar-duplicación-dependiente-de-expresión" class="nav-link" data-scroll-target="#dupradar-duplicación-dependiente-de-expresión"><span class="header-section-number">6.9.3</span> dupRadar: duplicación dependiente de expresión</a></li>
  <li><a href="#preseq-complejidad-molecular" id="toc-preseq-complejidad-molecular" class="nav-link" data-scroll-target="#preseq-complejidad-molecular"><span class="header-section-number">6.9.4</span> Preseq: complejidad molecular</a></li>
  <li><a href="#featurecounts-biotipos-asignados" id="toc-featurecounts-biotipos-asignados" class="nav-link" data-scroll-target="#featurecounts-biotipos-asignados"><span class="header-section-number">6.9.5</span> featureCounts: biotipos asignados</a></li>
  <li><a href="#herramientas-no-ejecutadas-trim-galore" id="toc-herramientas-no-ejecutadas-trim-galore" class="nav-link" data-scroll-target="#herramientas-no-ejecutadas-trim-galore"><span class="header-section-number">6.9.6</span> Herramientas no ejecutadas: Trim Galore</a></li>
  </ul></li>
  <li><a href="#qc-estadístico-de-las-matrices-de-expresión-en-r" id="toc-qc-estadístico-de-las-matrices-de-expresión-en-r" class="nav-link" data-scroll-target="#qc-estadístico-de-las-matrices-de-expresión-en-r"><span class="header-section-number">6.10</span> QC estadístico de las matrices de expresión en R</a>
  <ul class="collapse">
  <li><a href="#pca-global-del-proyecto" id="toc-pca-global-del-proyecto" class="nav-link" data-scroll-target="#pca-global-del-proyecto"><span class="header-section-number">6.10.1</span> PCA global del proyecto</a></li>
  <li><a href="#pca-del-conjunto-analítico-de-piel" id="toc-pca-del-conjunto-analítico-de-piel" class="nav-link" data-scroll-target="#pca-del-conjunto-analítico-de-piel"><span class="header-section-number">6.10.2</span> PCA del conjunto analítico de piel</a></li>
  <li><a href="#distancias-entre-muestras" id="toc-distancias-entre-muestras" class="nav-link" data-scroll-target="#distancias-entre-muestras"><span class="header-section-number">6.10.3</span> Distancias entre muestras</a></li>
  </ul></li>
  <li><a href="#conclusión-del-qc-integrado" id="toc-conclusión-del-qc-integrado" class="nav-link" data-scroll-target="#conclusión-del-qc-integrado"><span class="header-section-number">6.11</span> Conclusión del QC integrado</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Control de calidad integrado con MultiQC</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El informe <strong><a href="https://seqera.io/multiqc/">MultiQC</a></strong> se utiliza aquí como una fuente estructurada de resultados, no como una captura aislada <span class="citation" data-cites="Ewels2016MultiQC">[<a href="01_intro.html#ref-Ewels2016MultiQC" role="doc-biblioref">1</a>]</span>. La idea es que el lector pueda seguir el control de calidad <strong>herramienta por herramienta</strong>, viendo las mismas figuras exportadas por MultiQC y consultando las tablas originales en formato copiable.</p>
<p>Este capítulo documenta los módulos principales generados por <strong><a href="https://nf-co.re/rnaseq"><code>nf-core/rnaseq</code></a></strong> en la rama <code>star_salmon</code>, ejecutada sobre <strong><a href="https://www.nextflow.io/">Nextflow</a></strong> <span class="citation" data-cites="Ewels2020Nfcore DiTommaso2017Nextflow">[<a href="01_intro.html#ref-Ewels2020Nfcore" role="doc-biblioref">2</a>,<a href="01_intro.html#ref-DiTommaso2017Nextflow" role="doc-biblioref">3</a>]</span>: <strong>fastp</strong>, <strong>STAR</strong>, <strong>Samtools</strong>, <strong>Picard</strong>, <strong>strand check</strong> y <strong>versiones de software</strong>. Además, integra el análisis post-alineamiento recuperado mediante <code>--resume</code> sobre los BAM ya generados: <strong>Qualimap</strong>, <strong>RSeQC</strong>, <strong>dupRadar</strong>, <strong>Preseq</strong> y <strong>featureCounts</strong>. La interpretación combina dos niveles: una lectura <em>técnica</em>, centrada en si las bibliotecas son válidas para el análisis downstream, y una lectura <em>biológica</em>, centrada en si los resultados permiten confiar en la señal transcriptómica posterior.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Informe original">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Informe original
</div>
</div>
<div class="callout-body-container callout-body">
<p>El informe MultiQC completo se conserva como anexo navegable. Las secciones siguientes integran sus figuras y tablas principales dentro del libro, pero el HTML original sigue disponible para inspección interactiva.</p>
<div class="multiqc-link-row">
<p><a class="btn btn-primary" href="../multiqc/star_salmon/multiqc_report.html" target="_blank" rel="noopener">Abrir informe MultiQC completo</a> <a class="btn btn-primary" href="../multiqc/bam_qc/multiqc_report.html" target="_blank" rel="noopener">Abrir MultiQC post-alineamiento</a> <a class="btn btn-outline-secondary" href="../multiqc/star_salmon/multiqc_report_data/multiqc_general_stats.txt" target="_blank" rel="noopener">Descargar tabla General Stats</a></p>
</div>
</div>
</div>
<section id="resumen-ejecutivo-del-qc" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="resumen-ejecutivo-del-qc"><span class="header-section-number">6.1</span> Resumen ejecutivo del QC</h2>
<p>El control de calidad global fue favorable. El lote contiene <strong>24 muestras</strong>, todas con tasas altas de filtrado y alineamiento. No se detectó un patrón técnico que justifique excluir muestras en esta fase. Algunos extremos moderados deben seguirse en PCA y análisis exploratorio, especialmente <code>P44</code>, <code>P47</code>, <code>P49</code> y <code>PNKIT</code>.</p>
<div class="metric-grid">
<div class="metric-card">
<p><strong>24</strong></p>
<p>Muestras procesadas por <a href="https://nf-co.re/rnaseq"><code>nf-core/rnaseq</code></a>.</p>
</div>
<div class="metric-card">
<p><strong>98.45%</strong></p>
<p>Retención media de lecturas tras <a href="https://github.com/OpenGene/fastp"><code>fastp</code></a>.</p>
</div>
<div class="metric-card">
<p><strong>97.52%</strong></p>
<p>Alineamiento medio total con <strong>STAR</strong>.</p>
</div>
<div class="metric-card">
<p><strong>90.09%</strong></p>
<p>Alineamiento único medio con <strong>STAR</strong>.</p>
</div>
<div class="metric-card">
<p><strong>97.0%</strong></p>
<p>Orientación media inferida como <em>reverse</em> por <a href="https://combine-lab.github.io/salmon/">Salmon</a>.</p>
</div>
</div>
<div id="tbl-qc-decision-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-qc-decision-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;6.1: Matriz de decisión técnica derivada de las tablas y figuras exportadas por MultiQC.
</figcaption>
<div aria-describedby="tbl-qc-decision-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Módulo MultiQC</th>
<th style="text-align: right;">Resultado observado</th>
<th>Decisión técnica</th>
<th>Lectura biológica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>fastp</code> filtering</td>
<td style="text-align: right;">Retención media <strong>98.45%</strong>; mínimo <strong>97.92%</strong> (<code>P49</code>)</td>
<td>Aceptar</td>
<td>No hay pérdida diferencial fuerte de lecturas</td>
</tr>
<tr class="even">
<td><code>fastp</code> Q30</td>
<td style="text-align: right;">Q30 post-filtrado medio <strong>94.71%</strong>; mínimo <strong>93.23%</strong> (<code>P49</code>)</td>
<td>Aceptar</td>
<td>Calidad suficiente para cuantificación transcriptómica</td>
</tr>
<tr class="odd">
<td><code>fastp</code> adapters</td>
<td style="text-align: right;">Media <strong>5.24%</strong>; máximo <strong>9.67%</strong> (<code>PNKIT</code>)</td>
<td>Aceptar con recorte</td>
<td>La señal de adaptadores queda controlada por trimming</td>
</tr>
<tr class="even">
<td><code>STAR</code> alignment</td>
<td style="text-align: right;">Media <strong>97.52%</strong>; mínimo <strong>96.31%</strong> (<code>P44</code>)</td>
<td>Aceptar</td>
<td>Buena compatibilidad muestra-referencia</td>
</tr>
<tr class="odd">
<td><code>STAR</code> unique alignment</td>
<td style="text-align: right;">Media <strong>90.09%</strong>; mínimo <strong>86.56%</strong> (<code>P44</code>)</td>
<td>Vigilar <code>P44</code></td>
<td>Revisar en PCA, no excluir por QC primario</td>
</tr>
<tr class="even">
<td><code>Picard</code> duplicates</td>
<td style="text-align: right;">Media <strong>54.31%</strong>; máximo <strong>78.80%</strong> (<code>P49</code>)</td>
<td>Vigilar complejidad</td>
<td>Interpretar junto con abundancia de transcritos y profundidad</td>
</tr>
<tr class="odd">
<td><code>Strand check</code></td>
<td style="text-align: right;"><strong>24/24</strong> muestras inferidas como <code>reverse</code></td>
<td>Aceptar</td>
<td>Diseño de biblioteca coherente</td>
</tr>
<tr class="even">
<td><code>Qualimap</code> RNA-seq QC</td>
<td style="text-align: right;"><strong>24/24</strong> muestras; sesgo 5’-3’ medio <strong>1.30</strong>; rango <strong>1.18-1.39</strong></td>
<td>Aceptar</td>
<td>No se observa degradación 5’/3’ marcada</td>
</tr>
<tr class="odd">
<td><code>RSeQC</code> infer experiment</td>
<td style="text-align: right;"><strong>24/24</strong> muestras; fracción <code>pe_antisense</code> media <strong>72.73%</strong></td>
<td>Aceptar con vigilancia de <code>PNKIT</code></td>
<td>Orientación mayoritaria compatible con biblioteca reverse</td>
</tr>
<tr class="even">
<td><code>dupRadar</code></td>
<td style="text-align: right;"><strong>24/24</strong> muestras; intercepto medio <strong>0.53</strong>; máximo <strong>1.57</strong> (<code>P49</code>)</td>
<td>Vigilar <code>P49</code></td>
<td>Separar duplicación técnica de genes altamente expresados</td>
</tr>
<tr class="odd">
<td><code>Preseq</code></td>
<td style="text-align: right;"><strong>24/24</strong> muestras con curvas de complejidad</td>
<td>Aceptar como auditoría de complejidad</td>
<td>No indica fallo global de complejidad de bibliotecas</td>
</tr>
<tr class="even">
<td><code>featureCounts</code> biotypes</td>
<td style="text-align: right;"><strong>24/24</strong> muestras; señal dominada por genes codificantes</td>
<td>Aceptar</td>
<td>La cuantificación cae mayoritariamente en biotipos esperados</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Criterio de interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Criterio de interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una muestra no se elimina por ser el mínimo o máximo de una métrica. En RNA-seq bulk, algunas métricas como duplicación o profundidad pueden variar por razones biológicas y técnicas. La exclusión requiere un patrón consistente de fallo, no un valor extremo aislado.</p>
</div>
</div>
</section>
<section id="general-statistics" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="general-statistics"><span class="header-section-number">6.2</span> General statistics</h2>
<p>La tabla <strong>General Statistics</strong> de MultiQC resume en una sola matriz las métricas clave de todos los módulos. Es el punto de partida para detectar si una muestra se separa simultáneamente en varias dimensiones de QC: calidad, trimming, alineamiento, duplicación y mapeo.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Lectura rápida">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Lectura rápida
</div>
</div>
<div class="callout-body-container callout-body">
<p>No hay una muestra que falle globalmente en todas las métricas. <code>P49</code> combina menor retención relativa, menor Q30 y mayor duplicación Picard, por lo que debe marcarse como muestra de seguimiento. <code>P44</code> presenta el alineamiento único más bajo, pero mantiene una tasa total de alineamiento alta.</p>
</div>
</div>
<details class="multiqc-details" open="">
<summary>
Tabla MultiQC: General Statistics
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/multiqc_general_stats.txt" data-caption="General Statistics exportada por MultiQC. La tabla se puede seleccionar en la web o copiar como TSV con el botón.">

</div>
</details>
</section>
<section id="fastp-filtrado-calidad-y-composición" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="fastp-filtrado-calidad-y-composición"><span class="header-section-number">6.3</span> <a href="https://github.com/OpenGene/fastp">fastp</a>: filtrado, calidad y composición</h2>
<p><a href="https://github.com/OpenGene/fastp"><code>fastp</code></a> es un preprocesador de FASTQ que combina <strong>control de calidad</strong>, <strong>detección/recorte de adaptadores</strong>, <strong>filtrado por calidad</strong>, evaluación de contenido de bases y generación de informes HTML/JSON <span class="citation" data-cites="Chen2018Fastp">[<a href="01_intro.html#ref-Chen2018Fastp" role="doc-biblioref">4</a>]</span>. En este apartado se evalúa si el paso de trimming conserva suficientes lecturas, elimina señales técnicas evidentes y deja perfiles de calidad adecuados antes del alineamiento. En este proyecto, el filtrado fue homogéneo: la mayoría de las lecturas se conservaron y la calidad post-filtrado quedó en un rango alto.</p>
<div id="fig-multiqc-fastp-filtered" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-fastp-filtered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/star_salmon/multiqc_report_plots/svg/fastp_filtered_reads_plot-pct.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;6.1: Lecturas conservadas y descartadas tras el filtrado con fastp. La figura procede del SVG exportado por MultiQC."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/fastp_filtered_reads_plot-pct.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-fastp-filtered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: Lecturas conservadas y descartadas tras el filtrado con fastp. La figura procede del SVG exportado por MultiQC.
</figcaption>
</figure>
</div>
<p>La figura <a href="#fig-multiqc-fastp-filtered" class="quarto-xref">Figura&nbsp;<span>6.1</span></a> muestra que la fracción de lecturas descartadas es baja en todas las muestras. El mínimo de retención fue <code>P49</code> con <strong>97.92%</strong>, todavía dentro de un rango aceptable para RNA-seq bulk. La muestra <code>PNKIT</code> presentó la mayor señal de adaptadores (<strong>9.67%</strong>), pero mantuvo <strong>98.74%</strong> de lecturas retenidas, indicando que el recorte fue efectivo.</p>
<div id="fig-multiqc-fastp-quality" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-fastp-quality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-quality-plot_Read_1_After_filtering.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Read 1 después del filtrado."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-quality-plot_Read_1_After_filtering.svg" class="img-fluid figure-img"></a></p>
<figcaption>Read 1 después del filtrado.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-quality-plot_Read_2_After_filtering.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Read 2 después del filtrado."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-quality-plot_Read_2_After_filtering.svg" class="img-fluid figure-img"></a></p>
<figcaption>Read 2 después del filtrado.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-fastp-quality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.2: Calidad por ciclo después del filtrado con <code>fastp</code>. Las curvas altas y homogéneas apoyan que la señal de baja calidad fue eliminada antes del alineamiento.
</figcaption>
</figure>
</div>
<div id="fig-multiqc-fastp-gc" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-fastp-gc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-content-gc-plot_Read_1_After_filtering.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Contenido GC de Read 1 después del filtrado."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-content-gc-plot_Read_1_After_filtering.svg" class="img-fluid figure-img"></a></p>
<figcaption>Contenido GC de Read 1 después del filtrado.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-content-gc-plot_Read_2_After_filtering.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Contenido GC de Read 2 después del filtrado."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-seq-content-gc-plot_Read_2_After_filtering.svg" class="img-fluid figure-img"></a></p>
<figcaption>Contenido GC de Read 2 después del filtrado.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-fastp-gc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.3: Contenido GC por ciclo tras el filtrado. No se observa una desviación extrema que sugiera contaminación o sesgo fuerte de composición.
</figcaption>
</figure>
</div>
<div id="fig-multiqc-fastp-insert" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-fastp-insert-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-insert-size-plot.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figura&nbsp;6.4: Distribución de tamaños de inserto estimada por fastp."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/fastp-insert-size-plot.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-fastp-insert-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.4: Distribución de tamaños de inserto estimada por fastp.
</figcaption>
</figure>
</div>
<p>La distribución de tamaños de inserto en <a href="#fig-multiqc-fastp-insert" class="quarto-xref">Figura&nbsp;<span>6.4</span></a> es útil para comprobar que las bibliotecas paired-end tienen una geometría razonable. Una distribución coherente reduce el riesgo de problemas graves de preparación de biblioteca o de mezcla de muestras.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC: fastp filtered reads
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/fastp_filtered_reads_plot.txt" data-caption="Tabla de lecturas pasadas y descartadas por fastp, exportada por MultiQC.">

</div>
</details>
<section id="interpretación-técnica-y-biológica-de-fastp" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="interpretación-técnica-y-biológica-de-fastp"><span class="header-section-number">6.3.1</span> Interpretación técnica y biológica de fastp</h3>
<p>Técnicamente, <code>fastp</code> no detecta una degradación generalizada del lote. La combinación de alta retención, Q30 elevado y perfiles GC estables apoya continuar con el alineamiento. Biológicamente, esto es importante porque reduce la probabilidad de que las diferencias de expresión posteriores estén impulsadas por pérdidas diferenciales de lectura entre condiciones.</p>
</section>
</section>
<section id="star-alineamiento-contra-el-genoma-de-referencia" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="star-alineamiento-contra-el-genoma-de-referencia"><span class="header-section-number">6.4</span> <a href="https://github.com/alexdobin/STAR">STAR</a>: alineamiento contra el genoma de referencia</h2>
<p><a href="https://github.com/alexdobin/STAR"><code>STAR</code></a> es un alineador de RNA-seq diseñado para mapear lecturas contra un genoma de referencia teniendo en cuenta la estructura discontinua de los transcritos, especialmente los empalmes exon-exon <span class="citation" data-cites="Dobin2013STAR">[<a href="01_intro.html#ref-Dobin2013STAR" role="doc-biblioref">5</a>]</span>. En este apartado se evalúa si las lecturas filtradas son compatibles con la referencia genómica y si el porcentaje de alineamiento único es suficiente para cuantificación robusta. En este lote, el alineamiento total fue muy alto, con una media de <strong>97.52%</strong>. La muestra con menor alineamiento total fue <code>P44</code> (<strong>96.31%</strong>), que sigue siendo un valor sólido.</p>
<div id="fig-multiqc-star-alignment" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-star-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/star_salmon/multiqc_report_plots/svg/star_alignment_plot-pct.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figura&nbsp;6.5: Resumen de alineamiento STAR por muestra."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/star_alignment_plot-pct.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-star-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.5: Resumen de alineamiento STAR por muestra.
</figcaption>
</figure>
</div>
<p>La figura <a href="#fig-multiqc-star-alignment" class="quarto-xref">Figura&nbsp;<span>6.5</span></a> muestra una proporción dominante de lecturas alineadas en todas las muestras. El alineamiento único medio fue <strong>90.09%</strong>, con mínimo en <code>P44</code> (<strong>86.56%</strong>) y máximo en <code>P48</code> (<strong>91.71%</strong>). Esta variación no sugiere un fallo de referencia, contaminación general ni baja calidad masiva.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC: STAR summary
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/star_summary_table.txt" data-caption="Tabla completa de métricas STAR exportada por MultiQC.">

</div>
</details>
<div class="callout callout-style-default callout-note callout-titled" title="Lectura técnica">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lectura técnica
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>P44</code> queda como punto de vigilancia por su menor alineamiento único. La decisión correcta es conservarla en esta fase y comprobar si se comporta como outlier en PCA, clustering de muestras y distribución de conteos.</p>
</div>
</div>
</section>
<section id="samtools-métricas-de-bam-alineado" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="samtools-métricas-de-bam-alineado"><span class="header-section-number">6.5</span> <a href="https://www.htslib.org/">Samtools</a>: métricas de BAM alineado</h2>
<p><a href="https://www.htslib.org/"><code>Samtools</code></a> es una suite para manipular y auditar archivos de alineamiento en formatos SAM/BAM/CRAM <span class="citation" data-cites="Danecek2021Samtools">[<a href="01_intro.html#ref-Danecek2021Samtools" role="doc-biblioref">6</a>]</span>. En este apartado se comprueba el comportamiento de los BAM después del alineamiento: proporción de lecturas mapeadas, pares correctamente emparejados, flags de alineamiento y consistencia general del archivo alineado. Sus paneles funcionan como una comprobación posterior a STAR. En este run no aparece una señal global de BAM problemático.</p>
<div id="fig-multiqc-samtools-alignment" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-samtools-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/star_salmon/multiqc_report_plots/svg/samtools_alignment_plot-pct.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figura&nbsp;6.6: Resumen de alineamiento de Samtools."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/samtools_alignment_plot-pct.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-samtools-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.6: Resumen de alineamiento de Samtools.
</figcaption>
</figure>
</div>
<p>La figura <a href="#fig-multiqc-samtools-alignment" class="quarto-xref">Figura&nbsp;<span>6.6</span></a> complementa a STAR y confirma que las muestras mantienen un comportamiento consistente una vez generados los BAM. Las tablas originales se conservan abajo para auditoría y copia directa.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC: Samtools flagstat counts
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/samtools-flagstat-table.txt" data-caption="Tabla Samtools flagstat con conteos exportada por MultiQC.">

</div>
</details>
<details class="multiqc-details">
<summary>
Tabla MultiQC: Samtools flagstat percentages
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/samtools-flagstat-pct-table.txt" data-caption="Tabla Samtools flagstat con porcentajes exportada por MultiQC.">

</div>
</details>
</section>
<section id="picard-duplicación-y-complejidad-de-biblioteca" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="picard-duplicación-y-complejidad-de-biblioteca"><span class="header-section-number">6.6</span> <a href="https://broadinstitute.github.io/picard/">Picard</a>: duplicación y complejidad de biblioteca</h2>
<p><a href="https://broadinstitute.github.io/picard/"><code>Picard</code></a> es un conjunto de herramientas para manipular datos de secuenciación en formatos SAM/BAM/CRAM y VCF <span class="citation" data-cites="BroadInstitutePicard">[<a href="01_intro.html#ref-BroadInstitutePicard" role="doc-biblioref">7</a>]</span>. Aquí se usa el módulo <code>MarkDuplicates</code>, que estima duplicación a nivel de alineamiento. Este valor suele ser más alto que la duplicación aproximada de <code>fastp</code> porque se calcula después del mapeo y considera pares alineados y coordenadas genómicas. En el lote, la duplicación Picard media fue <strong>54.31%</strong>, con mínimo en <code>IT1G</code> (<strong>26.09%</strong>) y máximo en <code>P49</code> (<strong>78.80%</strong>).</p>
<div id="fig-multiqc-picard-dups" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-picard-dups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/star_salmon/multiqc_report_plots/svg/picard_deduplication-pct.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figura&nbsp;6.7: Duplicación estimada por Picard MarkDuplicates."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/picard_deduplication-pct.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-picard-dups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.7: Duplicación estimada por Picard MarkDuplicates.
</figcaption>
</figure>
</div>
<p>La figura <a href="#fig-multiqc-picard-dups" class="quarto-xref">Figura&nbsp;<span>6.7</span></a> no debe leerse como un criterio automático de exclusión. En RNA-seq, una duplicación alta puede reflejar baja complejidad técnica, pero también la presencia de transcritos muy abundantes. La interpretación final debe cruzarse con profundidad, PCA y distribución de expresión.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC: Picard MarkDuplicates
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/multiqc_picard_dups.txt" data-caption="Tabla Picard MarkDuplicates exportada por MultiQC.">

</div>
</details>
<div class="callout callout-style-default callout-warning callout-titled" title="Puntos de seguimiento">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Puntos de seguimiento
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>P49</code>, <code>P43</code>, <code>P47</code> y <code>P44</code> presentan duplicación Picard alta. No se descartan aquí, pero conviene revisarlas en la exploración multivariante y comprobar si concentran patrones de expresión anómalos.</p>
</div>
</div>
</section>
<section id="salmon-strand-check-orientación-de-la-biblioteca" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="salmon-strand-check-orientación-de-la-biblioteca"><span class="header-section-number">6.7</span> <a href="https://combine-lab.github.io/salmon/">Salmon</a> / strand check: orientación de la biblioteca</h2>
<p><a href="https://combine-lab.github.io/salmon/">Salmon</a> es una herramienta de cuantificación transcriptómica rápida y consciente de sesgos que puede inferir propiedades de la biblioteca durante el proceso de cuantificación <span class="citation" data-cites="Patro2017Salmon">[<a href="01_intro.html#ref-Patro2017Salmon" role="doc-biblioref">8</a>]</span>. En este apartado, el módulo de <em>strand check</em> compara la orientación esperada con la orientación inferida por Salmon a partir de las lecturas. Esta comprobación permite detectar errores de configuración de strandedness o mezcla de bibliotecas con orientaciones incompatibles. En este análisis, las <strong>24/24 muestras</strong> fueron inferidas como <code>reverse</code>, con una proporción media de <strong>97.0%</strong> y rango aproximado <strong>96.6-97.6%</strong>.</p>
<div id="fig-multiqc-strand-check" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiqc-strand-check-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/star_salmon/multiqc_report_plots/svg/strand_check_composition_bargraph.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figura&nbsp;6.8: Composición de orientación inferida por strand check."><img src="../multiqc/star_salmon/multiqc_report_plots/svg/strand_check_composition_bargraph.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiqc-strand-check-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.8: Composición de orientación inferida por strand check.
</figcaption>
</figure>
</div>
<p>La coherencia en <a href="#fig-multiqc-strand-check" class="quarto-xref">Figura&nbsp;<span>6.8</span></a> es una buena señal de reproducibilidad técnica: no hay evidencia de mezcla de orientación entre bibliotecas ni de configuración incorrecta de strandedness en el pipeline.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC: strand check summary
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/multiqc_strand_check_summary_table.txt" data-caption="Tabla de orientación inferida exportada por MultiQC.">

</div>
</details>
</section>
<section id="versiones-de-software" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="versiones-de-software"><span class="header-section-number">6.8</span> Versiones de software</h2>
<p>La reproducibilidad del análisis depende de fijar no solo los parámetros, sino también las versiones de software. MultiQC exporta una tabla de versiones por proceso, que se conserva aquí como parte del registro computacional del proyecto. Esta tabla conecta el resultado biológico con el entorno computacional real: pipeline, módulos, herramientas y versiones ejecutadas.</p>
<details class="multiqc-details" open="">
<summary>
Tabla MultiQC: software versions
</summary>
<div class="multiqc-table" data-src="../multiqc/star_salmon/multiqc_report_data/multiqc_software_versions.txt" data-caption="Versiones de software detectadas por MultiQC para los procesos del pipeline.">

</div>
</details>
</section>
<section id="qc-post-alineamiento-recuperado-con---resume" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="qc-post-alineamiento-recuperado-con---resume"><span class="header-section-number">6.9</span> QC post-alineamiento recuperado con <code>--resume</code></h2>
<p>El primer MultiQC integrado en este libro recogía el flujo principal <code>star_salmon</code>, pero no incluía de forma completa varios módulos post-alineamiento. Para completar esa parte se lanzó una segunda ejecución de <strong>nf-core/rnaseq</strong> con <code>--resume</code>, usando los <strong>BAM marcados como duplicados</strong> de la corrida original y activando los módulos de QC faltantes.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Nota sobre el nombre de carpeta `hisat2`">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Nota sobre el nombre de carpeta <code>hisat2</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los BAM evaluados proceden del alineamiento original con <strong>STAR</strong>. La carpeta <code>hisat2</code> aparece en la ejecución de recuperación por una decisión de configuración necesaria para evitar que nf-core/rnaseq reentrara en la rama de cuantificación <code>star_salmon</code> durante el reprocesado de BAM. Por tanto, las métricas de Qualimap, RSeQC, dupRadar, Preseq y featureCounts deben interpretarse como <strong>QC post-alineamiento de los BAM STAR originales</strong>.</p>
</div>
</div>
<p>El job de recuperación terminó correctamente (<strong>Slurm <code>COMPLETED</code>, exit code <code>0:0</code></strong>) y generó un MultiQC global con <strong>24/24 muestras</strong>. El informe completo queda publicado como anexo:</p>
<div class="multiqc-link-row">
<p><a class="btn btn-primary" href="../multiqc/bam_qc/multiqc_report.html" target="_blank" rel="noopener">Abrir MultiQC post-alineamiento</a> <a class="btn btn-outline-secondary" href="../multiqc/bam_qc/multiqc_report_data/multiqc_general_stats.txt" target="_blank" rel="noopener">Descargar General Stats post-alineamiento</a></p>
</div>
<div id="tbl-bam-qc-modules" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bam-qc-modules-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;6.2: Estado actualizado de los módulos post-alineamiento tras el <code>--resume</code>.
</figcaption>
<div aria-describedby="tbl-bam-qc-modules-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Herramienta</th>
<th style="text-align: right;">Cobertura</th>
<th>Qué evalúa</th>
<th>Resultado principal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="http://qualimap.conesalab.org/"><code>Qualimap</code></a></td>
<td style="text-align: right;">24/24</td>
<td>Origen genómico, cobertura sobre cuerpo génico y sesgo 5’-3’</td>
<td>Sesgo 5’-3’ moderado, media <strong>1.30</strong>, rango <strong>1.18-1.39</strong></td>
</tr>
<tr class="even">
<td><a href="http://rseqc.sourceforge.net/"><code>RSeQC</code></a></td>
<td style="text-align: right;">24/24</td>
<td>BAM, orientación, distribución de lecturas, distancia interna, junctions y duplicación</td>
<td>Orientación mayoritaria compatible con biblioteca reverse; <code>PNKIT</code> con fracción no determinada alta</td>
</tr>
<tr class="odd">
<td><a href="https://bioconductor.org/packages/dupRadar/"><code>dupRadar</code></a></td>
<td style="text-align: right;">24/24</td>
<td>Duplicación dependiente del nivel de expresión</td>
<td>Intercepto medio <strong>0.53</strong>; máximo <strong>1.57</strong> en <code>P49</code></td>
</tr>
<tr class="even">
<td><a href="http://smithlabresearch.org/software/preseq/"><code>Preseq</code></a></td>
<td style="text-align: right;">24/24</td>
<td>Complejidad molecular y rendimiento esperado al resecuenciar</td>
<td>Curvas disponibles para todas las muestras; sin fallo global evidente</td>
</tr>
<tr class="odd">
<td><a href="https://subread.sourceforge.net/featureCounts.html"><code>featureCounts</code></a></td>
<td style="text-align: right;">24/24</td>
<td>Asignación de lecturas a biotipos anotados</td>
<td>La señal está dominada por genes codificantes, media <strong>98.89%</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="qualimap-origen-genómico-y-sesgo-de-cobertura" class="level3" data-number="6.9.1">
<h3 data-number="6.9.1" class="anchored" data-anchor-id="qualimap-origen-genómico-y-sesgo-de-cobertura"><span class="header-section-number">6.9.1</span> <a href="http://qualimap.conesalab.org/">Qualimap</a>: origen genómico y sesgo de cobertura</h3>
<p><a href="http://qualimap.conesalab.org/"><code>Qualimap</code></a> evalúa la calidad de alineamientos de secuenciación y, en modo RNA-seq, resume cómo se distribuyen las lecturas respecto a la anotación: regiones exónicas, intrónicas, intergénicas, lecturas en junctions y perfil de cobertura a lo largo del cuerpo génico <span class="citation" data-cites="GarciaAlcalde2012Qualimap">[<a href="01_intro.html#ref-GarciaAlcalde2012Qualimap" role="doc-biblioref">9</a>]</span>.</p>
<p>En esta recuperación, Qualimap se generó para <strong>24/24 muestras</strong>. El sesgo 5’-3’ fue bajo-moderado, con media <strong>1.30</strong>, mínimo <strong>1.18</strong> (<code>P49</code>) y máximo <strong>1.39</strong> (<code>P44</code>). Esto no sugiere degradación extrema ni un sesgo sistemático fuerte a lo largo del cuerpo génico.</p>
<div id="fig-qualimap-bamqc" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qualimap-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/bam_qc/multiqc_report_plots/png/qualimap_genomic_origin-pct.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Origen genómico de las lecturas estimado por Qualimap."><img src="../multiqc/bam_qc/multiqc_report_plots/png/qualimap_genomic_origin-pct.png" class="img-fluid figure-img"></a></p>
<figcaption>Origen genómico de las lecturas estimado por Qualimap.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/bam_qc/multiqc_report_plots/png/qualimap_gene_coverage_profile_Normalised.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Perfil normalizado de cobertura sobre genes."><img src="../multiqc/bam_qc/multiqc_report_plots/png/qualimap_gene_coverage_profile_Normalised.png" class="img-fluid figure-img"></a></p>
<figcaption>Perfil normalizado de cobertura sobre genes.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qualimap-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.9: Resumen Qualimap del QC post-alineamiento. El origen genómico ayuda a evaluar la compatibilidad con la anotación, mientras que el perfil de cobertura permite detectar sesgos 5’-3’ o degradación.
</figcaption>
</figure>
</div>
<p>La proporción relativa de lecturas exónicas, intrónicas e intergénicas debe leerse con prudencia. En transcriptómica de especies con anotación perfectible, una fracción intergénica o intrónica apreciable no implica automáticamente contaminación; puede reflejar anotaciones incompletas, transcritos no anotados, pre-mRNA o regiones reguladoras transcritas.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC BAM-QC: Qualimap RNA-seq genome results
</summary>
<div class="multiqc-table" data-src="../multiqc/bam_qc/multiqc_report_data/qualimap_rnaseq_genome_results.txt" data-caption="Resultados de Qualimap RNA-seq exportados por MultiQC para las 24 muestras.">

</div>
</details>
</section>
<section id="rseqc-coherencia-de-bam-biblioteca-y-anotación" class="level3" data-number="6.9.2">
<h3 data-number="6.9.2" class="anchored" data-anchor-id="rseqc-coherencia-de-bam-biblioteca-y-anotación"><span class="header-section-number">6.9.2</span> <a href="http://rseqc.sourceforge.net/">RSeQC</a>: coherencia de BAM, biblioteca y anotación</h3>
<p><a href="http://rseqc.sourceforge.net/"><code>RSeQC</code></a> es un conjunto de módulos de control de calidad para RNA-seq alineado <span class="citation" data-cites="Wang2012RSeQC">[<a href="01_intro.html#ref-Wang2012RSeQC" role="doc-biblioref">10</a>]</span>. A diferencia de STAR o Samtools, que resumen métricas generales de mapeo, RSeQC entra en detalles propios del RNA-seq: distribución de lecturas sobre genes, compatibilidad con la orientación de biblioteca, saturación de junctions, distancia interna entre pares y patrones de duplicación.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="" aria-current="page">Orientación</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Distribución</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Distancia interna</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Junctions</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">Duplicación</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div id="fig-rseqc-infer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rseqc-infer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_infer_experiment_plot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figura&nbsp;6.10: Orientación de biblioteca inferida por RSeQC."><img src="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_infer_experiment_plot.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rseqc-infer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.10: Orientación de biblioteca inferida por RSeQC.
</figcaption>
</figure>
</div>
<p>El patrón dominante corresponde a <code>pe_antisense</code>, con media <strong>72.73%</strong>, compatible con bibliotecas de orientación reverse. La fracción no determinada fue baja en la mayoría de muestras, aunque <code>PNKIT</code> alcanzó <strong>45.34%</strong> y queda como punto de vigilancia técnico. Esta observación se interpreta junto con el <code>strand check</code> de Salmon, que fue coherente en las 24 muestras.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div id="fig-rseqc-read-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rseqc-read-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_read_distribution_plot-pct.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figura&nbsp;6.11: Distribución porcentual de lecturas sobre elementos génicos según RSeQC."><img src="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_read_distribution_plot-pct.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rseqc-read-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.11: Distribución porcentual de lecturas sobre elementos génicos según RSeQC.
</figcaption>
</figure>
</div>
<p>La distribución de lecturas se concentra mayoritariamente en regiones codificantes y UTR, con una contribución intrónica media moderada. Esta señal es compatible con bibliotecas RNA-seq de mRNA y no muestra un patrón global de contaminación o fallo de anotación.</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div id="fig-rseqc-inner-distance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rseqc-inner-distance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_inner_distance_plot_Counts.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figura&nbsp;6.12: Distribución de distancia interna entre pares de lectura."><img src="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_inner_distance_plot_Counts.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rseqc-inner-distance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.12: Distribución de distancia interna entre pares de lectura.
</figcaption>
</figure>
</div>
<p>La distancia interna evalúa la geometría paired-end después del alineamiento. Las distribuciones son útiles para detectar bibliotecas con inserto inesperado, colapso de fragmentos o comportamiento anómalo de pares.</p>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div id="fig-rseqc-junction-saturation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rseqc-junction-saturation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_junction_saturation_plot_Known_Junctions.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Figura&nbsp;6.13: Saturación de junctions conocidas."><img src="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_junction_saturation_plot_Known_Junctions.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rseqc-junction-saturation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.13: Saturación de junctions conocidas.
</figcaption>
</figure>
</div>
<p>La saturación de junctions permite valorar si la profundidad de secuenciación captura de forma estable los eventos de empalme detectables. No se observa una muestra aislada que rompa de manera evidente la tendencia del lote.</p>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<div id="fig-rseqc-read-dups" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rseqc-read-dups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_read_dups_plot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Figura&nbsp;6.14: Duplicación de lecturas estimada por RSeQC."><img src="../multiqc/bam_qc/multiqc_report_plots/png/rseqc_read_dups_plot.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rseqc-read-dups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.14: Duplicación de lecturas estimada por RSeQC.
</figcaption>
</figure>
</div>
<p>Este panel complementa Picard y dupRadar. En RNA-seq, la duplicación se interpreta siempre junto con expresión génica: transcritos muy abundantes pueden producir duplicación elevada sin que exista necesariamente fallo de biblioteca.</p>
</div>
</div>
</div>
<details class="multiqc-details">
<summary>
Tabla MultiQC BAM-QC: RSeQC infer experiment
</summary>
<div class="multiqc-table" data-src="../multiqc/bam_qc/multiqc_report_data/multiqc_rseqc_infer_experiment.txt" data-caption="Orientación de biblioteca inferida por RSeQC.">

</div>
</details>
<details class="multiqc-details">
<summary>
Tabla MultiQC BAM-QC: RSeQC read distribution
</summary>
<div class="multiqc-table" data-src="../multiqc/bam_qc/multiqc_report_data/multiqc_rseqc_read_distribution.txt" data-caption="Distribución de lecturas sobre regiones génicas según RSeQC.">

</div>
</details>
</section>
<section id="dupradar-duplicación-dependiente-de-expresión" class="level3" data-number="6.9.3">
<h3 data-number="6.9.3" class="anchored" data-anchor-id="dupradar-duplicación-dependiente-de-expresión"><span class="header-section-number">6.9.3</span> <a href="https://bioconductor.org/packages/dupRadar/">dupRadar</a>: duplicación dependiente de expresión</h3>
<p><a href="https://bioconductor.org/packages/dupRadar/"><code>dupRadar</code></a> evalúa si la duplicación aumenta de forma esperable con el nivel de expresión o si existe una señal compatible con artefactos de PCR <span class="citation" data-cites="Sayols2016DupRadar">[<a href="01_intro.html#ref-Sayols2016DupRadar" role="doc-biblioref">11</a>]</span>. Esto es especialmente útil en RNA-seq: los genes muy expresados tienden a generar más lecturas duplicadas incluso en bibliotecas técnicamente válidas.</p>
<div id="fig-dupradar-bamqc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dupradar-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/dupradar.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figura&nbsp;6.15: Relación entre duplicación y expresión estimada por dupRadar."><img src="../multiqc/bam_qc/multiqc_report_plots/png/dupradar.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dupradar-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.15: Relación entre duplicación y expresión estimada por dupRadar.
</figcaption>
</figure>
</div>
<p>El intercepto dupRadar se calculó para <strong>24/24 muestras</strong>. La media fue <strong>0.53</strong>, con mínimo <strong>0.08</strong> (<code>PNKIT</code>) y máximo <strong>1.57</strong> (<code>P49</code>). <code>P49</code> confirma el patrón observado previamente con Picard: tiene una señal de duplicación mayor que el resto y debe seguirse en PCA y análisis exploratorio. Aun así, la presencia de duplicación dependiente de expresión no equivale por sí sola a un fallo técnico, especialmente si la muestra mantiene buen alineamiento y buena calidad de lectura.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC BAM-QC: General Stats con intercepto dupRadar
</summary>
<div class="multiqc-table" data-src="../multiqc/bam_qc/multiqc_report_data/multiqc_general_stats.txt" data-caption="General Stats del MultiQC post-alineamiento, incluyendo intercepto dupRadar, métricas Qualimap y RSeQC.">

</div>
</details>
</section>
<section id="preseq-complejidad-molecular" class="level3" data-number="6.9.4">
<h3 data-number="6.9.4" class="anchored" data-anchor-id="preseq-complejidad-molecular"><span class="header-section-number">6.9.4</span> <a href="http://smithlabresearch.org/software/preseq/">Preseq</a>: complejidad molecular</h3>
<p><a href="http://smithlabresearch.org/software/preseq/"><code>Preseq</code></a> extrapola la complejidad molecular de una biblioteca y estima cuánta señal nueva se esperaría al aumentar la profundidad de secuenciación <span class="citation" data-cites="Daley2013Preseq">[<a href="01_intro.html#ref-Daley2013Preseq" role="doc-biblioref">12</a>]</span>. A diferencia de Picard o RSeQC, que miden duplicación observada, Preseq intenta proyectar el rendimiento potencial de resecuenciar la misma biblioteca.</p>
<div id="fig-preseq-bamqc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-preseq-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../multiqc/bam_qc/multiqc_report_plots/png/preseq_complexity_plot_molecules.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Figura&nbsp;6.16: Curvas de complejidad molecular estimadas por Preseq."><img src="../multiqc/bam_qc/multiqc_report_plots/png/preseq_complexity_plot_molecules.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-preseq-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.16: Curvas de complejidad molecular estimadas por Preseq.
</figcaption>
</figure>
</div>
<p>Preseq se generó para <strong>24/24 muestras</strong>. Las curvas son coherentes con bibliotecas de RNA-seq bulk donde la ganancia de moléculas nuevas se desacelera al aumentar la profundidad. No se detecta una señal global que obligue a excluir muestras por complejidad, aunque las curvas deben interpretarse junto con duplicación, profundidad y distribución de expresión.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Tabla Preseq">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tabla Preseq
</div>
</div>
<div class="callout-body-container callout-body">
<p>La tabla <code>preseq.txt</code> tiene muchas columnas porque exporta la curva completa de extrapolación. Por eso no se renderiza como tabla copiable dentro de la página, para no hacer pesada la navegación. Se conserva en el anexo MultiQC: <a href="../multiqc/bam_qc/multiqc_report_data/preseq.txt">descargar <code>preseq.txt</code></a>.</p>
</div>
</div>
</section>
<section id="featurecounts-biotipos-asignados" class="level3" data-number="6.9.5">
<h3 data-number="6.9.5" class="anchored" data-anchor-id="featurecounts-biotipos-asignados"><span class="header-section-number">6.9.5</span> <a href="https://subread.sourceforge.net/featureCounts.html">featureCounts</a>: biotipos asignados</h3>
<p><a href="https://subread.sourceforge.net/featureCounts.html"><code>featureCounts</code></a>, parte del paquete Subread, asigna lecturas alineadas a features genómicas anotadas de forma eficiente <span class="citation" data-cites="Liao2014FeatureCounts">[<a href="01_intro.html#ref-Liao2014FeatureCounts" role="doc-biblioref">13</a>]</span>. En este QC se utiliza para resumir la contribución relativa de distintos biotipos, como genes codificantes, lncRNA, rRNA, snRNA o pseudogenes.</p>
<div id="fig-featurecounts-bamqc" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-featurecounts-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/bam_qc/multiqc_report_plots/png/featurecounts_biotype_plot-pct.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Biotipos asignados por featureCounts, porcentajes."><img src="../multiqc/bam_qc/multiqc_report_plots/png/featurecounts_biotype_plot-pct.png" class="img-fluid figure-img"></a></p>
<figcaption>Biotipos asignados por featureCounts, porcentajes.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../multiqc/bam_qc/multiqc_report_plots/png/featurecounts_biotype_plot-cnt.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="Biotipos asignados por featureCounts, conteos."><img src="../multiqc/bam_qc/multiqc_report_plots/png/featurecounts_biotype_plot-cnt.png" class="img-fluid figure-img"></a></p>
<figcaption>Biotipos asignados por featureCounts, conteos.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-featurecounts-bamqc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.17: Distribución de biotipos estimada por featureCounts. La dominancia de genes codificantes es compatible con bibliotecas de mRNA enriquecidas por poli(A).
</figcaption>
</figure>
</div>
<p>La señal está fuertemente dominada por genes <strong>protein_coding</strong>, con una proporción media aproximada de <strong>98.89%</strong> entre los biotipos representados en la tabla exportada. Esto es coherente con bibliotecas de mRNA y no sugiere una contaminación masiva por biotipos no esperados.</p>
<details class="multiqc-details">
<summary>
Tabla MultiQC BAM-QC: featureCounts biotypes
</summary>
<div class="multiqc-table" data-src="../multiqc/bam_qc/multiqc_report_data/multiqc_featurecounts_biotype_plot.txt" data-caption="Conteos por biotipo exportados por featureCounts y resumidos por MultiQC.">

</div>
</details>
</section>
<section id="herramientas-no-ejecutadas-trim-galore" class="level3" data-number="6.9.6">
<h3 data-number="6.9.6" class="anchored" data-anchor-id="herramientas-no-ejecutadas-trim-galore"><span class="header-section-number">6.9.6</span> Herramientas no ejecutadas: Trim Galore</h3>
<p><a href="https://github.com/FelixKrueger/TrimGalore"><code>Trim Galore</code></a> no se ejecutó en este proyecto. El recorte de adaptadores y filtrado de lecturas fue realizado por <strong>fastp</strong>, que ya está documentado arriba. Por tanto, la ausencia de Trim Galore no representa una pérdida de resultados: responde a la configuración del pipeline.</p>
</section>
</section>
<section id="qc-estadístico-de-las-matrices-de-expresión-en-r" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="qc-estadístico-de-las-matrices-de-expresión-en-r"><span class="header-section-number">6.10</span> QC estadístico de las matrices de expresión en R</h2>
<p>El QC de MultiQC evalúa la calidad técnica de lecturas, alineamientos y BAMs. La siguiente capa de control se realizó en <strong>R</strong> sobre las matrices de expresión generadas por <code>Salmon</code>, usando conteos a nivel de gen, transformación estabilizadora de varianza de <code>DESeq2</code> y análisis no supervisados. Esta etapa responde a una pregunta distinta: si, una vez cuantificada la expresión, las muestras se agrupan de forma compatible con el diseño biológico y si alguna muestra muestra un comportamiento extremo que pueda sesgar el análisis diferencial.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Lectura práctica de esta sección">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Lectura práctica de esta sección
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una muestra no debe excluirse por una sola métrica aislada. En este proyecto se cruzaron <strong>calidad de lectura</strong>, <strong>mapeo</strong>, <strong>duplicación</strong>, <strong>profundidad de cuantificación</strong>, <strong>PCA</strong>, <strong>distancias entre muestras</strong> y <strong>coherencia con el diseño experimental</strong>. Este enfoque evita confundir variación biológica real con ruido técnico.</p>
</div>
</div>
<p>La tabla integrada de QC resume <strong>24 bibliotecas RNA-seq</strong>. De ellas, <strong>20 muestras de piel</strong> constituyen el conjunto principal de expresión diferencial. Cuatro muestras se mantienen en el QC exploratorio pero quedan fuera del análisis principal: <code>IT1G</code> y <code>PNKIT</code> por corresponder a intestino, y <code>PNKD</code>/<code>PNKV</code> por pertenecer al bloque exploratorio de ambicoloration/PNK.</p>
<table class="caption-top table">
<caption>Resumen cuantitativo del QC estadístico integrado a partir de las matrices de expresión y métricas de nf-core/MultiQC. Los valores proceden de la tabla <code>sample_basic_qc_summary.tsv</code>.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica</th>
<th style="text-align: right;">Resultado global</th>
<th style="text-align: right;">Mínimo</th>
<th style="text-align: right;">Máximo</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Supervivencia tras filtrado fastp (%)</td>
<td style="text-align: right;">98.45</td>
<td style="text-align: right;">97.92 (<code>P49</code>)</td>
<td style="text-align: right;">98.84 (<code>PNKD</code>)</td>
<td>Retención muy alta; no hay pérdidas severas por trimming.</td>
</tr>
<tr class="even">
<td>Alineamiento único STAR (%)</td>
<td style="text-align: right;">90.09</td>
<td style="text-align: right;">86.56 (<code>P44</code>)</td>
<td style="text-align: right;">91.71 (<code>P48</code>)</td>
<td>Mapeo sólido; <code>P44</code> se vigila por estar en el extremo inferior.</td>
</tr>
<tr class="odd">
<td>Duplicación Picard (%)</td>
<td style="text-align: right;">54.31</td>
<td style="text-align: right;">26.09 (<code>IT1G</code>)</td>
<td style="text-align: right;">78.80 (<code>P49</code>)</td>
<td>Señal técnica más destacable; requiere interpretación junto con expresión y PCA.</td>
</tr>
<tr class="even">
<td>Conteos génicos Salmon</td>
<td style="text-align: right;">10548121.37</td>
<td style="text-align: right;">8151700.02 (<code>P34</code>)</td>
<td style="text-align: right;">17807075.96 (<code>P33</code>)</td>
<td>Profundidad suficiente y sin bibliotecas colapsadas.</td>
</tr>
<tr class="odd">
<td>Genes detectados, conteo ≥ 10</td>
<td style="text-align: right;">13826.29</td>
<td style="text-align: right;">11678 (<code>P43</code>)</td>
<td style="text-align: right;">15583 (<code>P33</code>)</td>
<td>Complejidad aceptable; <code>P43</code> queda en el extremo bajo.</td>
</tr>
</tbody>
</table>
<p>Las muestras con señales de vigilancia fueron principalmente pseudoalbinas, en especial <code>P43</code>, <code>P44</code>, <code>P47</code> y <code>P49</code>. Todas conservan buena supervivencia de lecturas y cuantificación suficiente, pero combinan <strong>duplicación elevada</strong> y, en algunos casos, menor número de genes detectados o menor mapeo único. Por tanto, se tratan como muestras a seguir en PCA y análisis diferencial, no como descartes automáticos.</p>
<table class="caption-top table">
<caption>Muestras con señales de vigilancia técnica tras integrar métricas de alineamiento, duplicación y cuantificación. La decisión final se apoya en el comportamiento multivariante y en la coherencia con el diseño.</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Muestra</th>
<th>Grupo</th>
<th style="text-align: center;">Incluida en DE</th>
<th style="text-align: right;">STAR único (%)</th>
<th style="text-align: right;">Duplicación Picard (%)</th>
<th style="text-align: right;">Genes detectados ≥ 10</th>
<th>Lectura técnica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>P43</code></td>
<td><code>P_BD</code></td>
<td style="text-align: center;">Sí</td>
<td style="text-align: right;">88.91</td>
<td style="text-align: right;">73.77</td>
<td style="text-align: right;">11678</td>
<td>Menor complejidad detectable; vigilar en análisis de distancia.</td>
</tr>
<tr class="even">
<td><code>P44</code></td>
<td><code>P_BL</code></td>
<td style="text-align: center;">Sí</td>
<td style="text-align: right;">86.56</td>
<td style="text-align: right;">70.79</td>
<td style="text-align: right;">12744</td>
<td>Mínimo de alineamiento único; revisar si domina algún contraste.</td>
</tr>
<tr class="odd">
<td><code>P47</code></td>
<td><code>P_BD</code></td>
<td style="text-align: center;">Sí</td>
<td style="text-align: right;">89.16</td>
<td style="text-align: right;">72.84</td>
<td style="text-align: right;">12397</td>
<td>Duplicación alta y complejidad moderada-baja.</td>
</tr>
<tr class="even">
<td><code>P49</code></td>
<td><code>P_OD</code></td>
<td style="text-align: center;">Sí</td>
<td style="text-align: right;">90.50</td>
<td style="text-align: right;">78.80</td>
<td style="text-align: right;">13116</td>
<td>Máxima duplicación Picard; no muestra fallo global de mapeo.</td>
</tr>
</tbody>
</table>
<div id="fig-qc-r-summary" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qc-r-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/03_qc_r/sample_basic_qc_overview.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Resumen por muestra de supervivencia al filtrado, alineamiento único y duplicación Picard."><img src="../figures/03_qc_r/sample_basic_qc_overview.png" class="img-fluid figure-img"></a></p>
<figcaption>Resumen por muestra de supervivencia al filtrado, alineamiento único y duplicación Picard.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/03_qc_r/read_count_yield_by_sample.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="Profundidad y rendimiento de conteos por muestra."><img src="../figures/03_qc_r/read_count_yield_by_sample.png" class="img-fluid figure-img"></a></p>
<figcaption>Profundidad y rendimiento de conteos por muestra.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qc-r-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.18: Resumen gráfico del QC estadístico integrado. La figura confirma que la calidad post-filtrado y el alineamiento son homogéneos, mientras que la duplicación presenta mayor dispersión, especialmente en algunas muestras pseudoalbinas.
</figcaption>
</figure>
</div>
<p>La cuantificación con <code>Salmon</code> no mostró bibliotecas fallidas. <code>P33</code> presenta la mayor profundidad y el mayor número de genes detectados, mientras que <code>P34</code> tiene el menor número total de conteos y <code>P43</code> el menor número de genes con conteo ≥ 10. Estos extremos son relevantes para interpretar dispersión y potencia estadística, pero no justifican exclusión por sí solos.</p>
<div id="fig-qc-r-salmon-libraries" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qc-r-salmon-libraries-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/03_qc_r/salmon_library_sizes.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="Figura&nbsp;6.19: Tamaños de librería y genes detectados en la matriz Salmon a nivel génico."><img src="../figures/03_qc_r/salmon_library_sizes.png" class="img-fluid figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qc-r-salmon-libraries-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.19: Tamaños de librería y genes detectados en la matriz Salmon a nivel génico.
</figcaption>
</figure>
</div>
<section id="pca-global-del-proyecto" class="level3" data-number="6.10.1">
<h3 data-number="6.10.1" class="anchored" data-anchor-id="pca-global-del-proyecto"><span class="header-section-number">6.10.1</span> PCA global del proyecto</h3>
<p>El PCA global incluye piel, intestino y muestras exploratorias de ambicoloration/PNK. La separación más fuerte corresponde al eje <strong>tejido</strong>, con las muestras intestinales alejadas claramente del bloque de piel en PC1. Esto es biológicamente esperable y confirma que las muestras de intestino no deben mezclarse con el análisis principal de piel. En la misma vista, las muestras de ambicoloration/PNK también quedan fuera del diseño inferencial principal, aunque son útiles como referencia exploratoria.</p>
<div id="fig-qc-r-pca-project" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qc-r-pca-project-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/03_qc_r/pca_all_project_uncorrected.png" class="lightbox" data-gallery="quarto-lightbox-gallery-25" title="Figura&nbsp;6.20: PCA no corregido con todas las muestras del proyecto. PC1 explica 71.9% de la varianza y separa fuertemente las muestras de intestino del conjunto de piel."><img src="../figures/03_qc_r/pca_all_project_uncorrected.png" class="img-fluid figure-img" style="width:95.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qc-r-pca-project-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.20: PCA no corregido con todas las muestras del proyecto. PC1 explica 71.9% de la varianza y separa fuertemente las muestras de intestino del conjunto de piel.
</figcaption>
</figure>
</div>
</section>
<section id="pca-del-conjunto-analítico-de-piel" class="level3" data-number="6.10.2">
<h3 data-number="6.10.2" class="anchored" data-anchor-id="pca-del-conjunto-analítico-de-piel"><span class="header-section-number">6.10.2</span> PCA del conjunto analítico de piel</h3>
<p>Al restringir el análisis a las <strong>20 muestras de piel</strong> incluidas en expresión diferencial, el PC1 explica <strong>76.6%</strong> de la variación y ordena las muestras según un gradiente compatible con <strong>superficie, pigmentación y estado fenotípico</strong>. No se observa una muestra aislada de forma extrema que obligue a descartar una biblioteca antes del modelado. Sí se aprecia que el diseño contiene una estructura biológica fuerte: las comparaciones deben interpretarse por contraste, no como una única separación “normal vs pseudoalbino”.</p>
<div id="fig-qc-r-pca-skin" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qc-r-pca-skin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/03_qc_r/pca_all_skin_uncorrected.png" class="lightbox" data-gallery="quarto-lightbox-gallery-26" title="Figura&nbsp;6.21: PCA no corregido de las muestras de piel usadas en el análisis principal. La separación dominante refleja estructura biológica del diseño, no un fallo técnico evidente."><img src="../figures/03_qc_r/pca_all_skin_uncorrected.png" class="img-fluid figure-img" style="width:95.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qc-r-pca-skin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.21: PCA no corregido de las muestras de piel usadas en el análisis principal. La separación dominante refleja estructura biológica del diseño, no un fallo técnico evidente.
</figcaption>
</figure>
</div>
<p>La PCA ajustada por fecha de muestreo se generó solo como diagnóstico visual. Tras retirar este componente, la ordenación cambia pero mantiene separación entre grupos, lo que sugiere que la fecha puede contribuir a la variabilidad global, pero no explica por completo la estructura de expresión. Por este motivo, la corrección por fecha se usa para <strong>exploración</strong>, mientras que los modelos de DESeq2 trabajan con conteos crudos y diseños estadísticos definidos por contraste.</p>
<div id="fig-qc-r-pca-skin-date" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qc-r-pca-skin-date-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/03_qc_r/pca_all_skin_date_adjusted.png" class="lightbox" data-gallery="quarto-lightbox-gallery-27" title="Figura&nbsp;6.22: PCA de piel tras ajuste visual por fecha de colección. La corrección reduce parte de la estructura temporal, pero persisten diferencias compatibles con superficie y pigmentación."><img src="../figures/03_qc_r/pca_all_skin_date_adjusted.png" class="img-fluid figure-img" style="width:95.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qc-r-pca-skin-date-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.22: PCA de piel tras ajuste visual por fecha de colección. La corrección reduce parte de la estructura temporal, pero persisten diferencias compatibles con superficie y pigmentación.
</figcaption>
</figure>
</div>
</section>
<section id="distancias-entre-muestras" class="level3" data-number="6.10.3">
<h3 data-number="6.10.3" class="anchored" data-anchor-id="distancias-entre-muestras"><span class="header-section-number">6.10.3</span> Distancias entre muestras</h3>
<p>El mapa de calor de distancias resume la similitud global entre perfiles transcriptómicos estabilizados. Su utilidad principal es detectar muestras que no se agrupan con réplicas o condiciones próximas. En este conjunto, la señal dominante sigue siendo la estructura del diseño y no aparece una muestra con comportamiento incompatible con su grupo que deba excluirse de entrada.</p>
<div id="fig-qc-r-sample-distance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qc-r-sample-distance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/03_qc_r/sample_distance_heatmap_skin_core.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="Figura&nbsp;6.23: Mapa de calor de distancias entre muestras de piel calculado sobre la matriz transformada por VST."><img src="../figures/03_qc_r/sample_distance_heatmap_skin_core.png" class="img-fluid figure-img" style="width:95.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qc-r-sample-distance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.23: Mapa de calor de distancias entre muestras de piel calculado sobre la matriz transformada por VST.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Decisión QC tras integrar R y MultiQC">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Decisión QC tras integrar R y MultiQC
</div>
</div>
<div class="callout-body-container callout-body">
<p>Se mantienen las <strong>20 muestras de piel</strong> del diseño principal para expresión diferencial. Las muestras <code>P43</code>, <code>P44</code>, <code>P47</code> y <code>P49</code> se etiquetan como puntos de vigilancia técnica, principalmente por duplicación y complejidad relativa, pero no presentan evidencia suficiente para ser eliminadas. Las muestras <code>IT1G</code>, <code>PNKIT</code>, <code>PNKD</code> y <code>PNKV</code> se conservan en el registro de QC, pero quedan fuera del análisis diferencial principal por diseño experimental.</p>
</div>
</div>
</section>
</section>
<section id="conclusión-del-qc-integrado" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="conclusión-del-qc-integrado"><span class="header-section-number">6.11</span> Conclusión del QC integrado</h2>
<p>El informe integrado apoya continuar con las salidas <code>star_salmon</code> como base del análisis downstream. La señal técnica principal es consistente: <strong>alta calidad post-filtrado</strong>, <strong>alineamiento sólido contra la referencia</strong>, <strong>orientación de biblioteca coherente</strong>, cuantificación estable y ausencia de un fallo global de muestra.</p>
<p>La lectura biológica es, por tanto, prudente pero positiva: si aparecen patrones fuertes en PCA o expresión diferencial, no hay evidencia de que deban atribuirse de entrada a un fallo general de secuenciación, alineamiento o cuantificación. Las muestras señaladas deben acompañar la interpretación, no bloquearla.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Decisión">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Decisión
</div>
</div>
<div class="callout-body-container callout-body">
<p>Se mantienen todas las bibliotecas para trazabilidad y exploración QC. El análisis diferencial principal se restringe a las <strong>20 muestras de piel</strong> definidas por el diseño experimental, excluyendo intestino y el bloque exploratorio PNK/ambicoloration.</p>
</div>
</div>
</section>
<section id="referencias" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Ewels2016MultiQC" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">Ewels P., Magnusson M., Lundin S., Kaller M. <span>MultiQC: summarize analysis results for multiple tools and samples in a single report</span>. Bioinformatics; 2016; 32(19):3047-3048. doi:<a href="https://doi.org/10.1093/bioinformatics/btw354">10.1093/bioinformatics/btw354</a> <a href="https://doi.org/10.1093/bioinformatics/btw354">https://doi.org/10.1093/bioinformatics/btw354</a></div>
</div>
<div id="ref-Ewels2020Nfcore" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">Ewels P. A., Peltzer A., Fillinger S., Patel H., Alneberg J., Wilm A., Garcia M. U., Di Tommaso P., Nahnsen S. <span>The nf-core framework for community-curated bioinformatics pipelines</span>. Nature Biotechnology; 2020; 38(3):276-278. doi:<a href="https://doi.org/10.1038/s41587-020-0439-x">10.1038/s41587-020-0439-x</a> <a href="https://doi.org/10.1038/s41587-020-0439-x">https://doi.org/10.1038/s41587-020-0439-x</a></div>
</div>
<div id="ref-DiTommaso2017Nextflow" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">Di Tommaso P., Chatzou M., Floden E. W., Barja P. P., Palumbo E., Notredame C. <span>Nextflow enables reproducible computational workflows</span>. Nature Biotechnology; 2017; 35(4):316-319. doi:<a href="https://doi.org/10.1038/nbt.3820">10.1038/nbt.3820</a> <a href="https://doi.org/10.1038/nbt.3820">https://doi.org/10.1038/nbt.3820</a></div>
</div>
<div id="ref-Chen2018Fastp" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">Chen S., Zhou Y., Chen Y., Gu J. <span>fastp: an ultra-fast all-in-one FASTQ preprocessor</span>. Bioinformatics; 2018; 34(17):i884-i890. doi:<a href="https://doi.org/10.1093/bioinformatics/bty560">10.1093/bioinformatics/bty560</a> <a href="https://doi.org/10.1093/bioinformatics/bty560">https://doi.org/10.1093/bioinformatics/bty560</a></div>
</div>
<div id="ref-Dobin2013STAR" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">Dobin A., Davis C. A., Schlesinger F., Drenkow J., Zaleski C., Jha S., Batut P., Chaisson M., Gingeras T. R. <span>STAR: ultrafast universal RNA-seq aligner</span>. Bioinformatics; 2013; 29(1):15-21. doi:<a href="https://doi.org/10.1093/bioinformatics/bts635">10.1093/bioinformatics/bts635</a> <a href="https://doi.org/10.1093/bioinformatics/bts635">https://doi.org/10.1093/bioinformatics/bts635</a></div>
</div>
<div id="ref-Danecek2021Samtools" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">Danecek P., Bonfield J. K., Liddle J., Marshall J., Ohan V., Pollard M. O., Whitwham A., Keane T., McCarthy S. A., Davies R. M., Li H. <span>Twelve years of SAMtools and BCFtools</span>. GigaScience; 2021; 10(2):giab008. doi:<a href="https://doi.org/10.1093/gigascience/giab008">10.1093/gigascience/giab008</a> <a href="https://doi.org/10.1093/gigascience/giab008">https://doi.org/10.1093/gigascience/giab008</a></div>
</div>
<div id="ref-BroadInstitutePicard" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">Broad Institute. <span>Picard toolkit</span>. 2026. <a href="https://broadinstitute.github.io/picard/">https://broadinstitute.github.io/picard/</a></div>
</div>
<div id="ref-Patro2017Salmon" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline">Patro R., Duggal G., Love M. I., Irizarry R. A., Kingsford C. <span>Salmon provides fast and bias-aware quantification of transcript expression</span>. Nature Methods; 2017; 14(4):417-419. doi:<a href="https://doi.org/10.1038/nmeth.4197">10.1038/nmeth.4197</a> <a href="https://doi.org/10.1038/nmeth.4197">https://doi.org/10.1038/nmeth.4197</a></div>
</div>
<div id="ref-GarciaAlcalde2012Qualimap" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline">García-Alcalde F., Okonechnikov K., Carbonell J., Cruz L. M., Götz S., Tarazona S., Dopazo J., Meyer T. F., Conesa A. <span>Qualimap: evaluating next-generation sequencing alignment data</span>. Bioinformatics; 2012; 28(20):2678-2679. doi:<a href="https://doi.org/10.1093/bioinformatics/bts503">10.1093/bioinformatics/bts503</a></div>
</div>
<div id="ref-Wang2012RSeQC" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline">Wang L., Wang S., Li W. <span>RSeQC: quality control of RNA-seq experiments</span>. Bioinformatics; 2012; 28(16):2184-2185. doi:<a href="https://doi.org/10.1093/bioinformatics/bts356">10.1093/bioinformatics/bts356</a></div>
</div>
<div id="ref-Sayols2016DupRadar" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div><div class="csl-right-inline">Sayols S., Scherzinger D., Klein H. <span>dupRadar: a Bioconductor package for the assessment of PCR artifacts in RNA-Seq data</span>. BMC Bioinformatics; 2016; 17(1):428. doi:<a href="https://doi.org/10.1186/s12859-016-1276-2">10.1186/s12859-016-1276-2</a></div>
</div>
<div id="ref-Daley2013Preseq" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div><div class="csl-right-inline">Daley T., Smith A. D. <span>Predicting the molecular complexity of sequencing libraries</span>. Nature Methods; 2013; 10(4):325-327. doi:<a href="https://doi.org/10.1038/nmeth.2375">10.1038/nmeth.2375</a></div>
</div>
<div id="ref-Liao2014FeatureCounts" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div><div class="csl-right-inline">Liao Y., Smyth G. K., Shi W. <span>featureCounts: an efficient general purpose program for assigning sequence reads to genomic features</span>. Bioinformatics; 2014; 30(7):923-930. doi:<a href="https://doi.org/10.1093/bioinformatics/btt656">10.1093/bioinformatics/btt656</a></div>
</div>
</div>
<script>
(function () {
  function splitTsv(text) {
    return text.replace(/\r?\n$/, "").split(/\r?\n/).map(function (line) {
      return line.split("\t");
    });
  }

  function isNumeric(value) {
    return /^[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?$/i.test(value.trim());
  }

  function formatValue(value) {
    var trimmed = value.trim();
    if (trimmed === "") return "";
    if (trimmed.toLowerCase() === "nan") return "NA";
    if (!isNumeric(trimmed)) return value;

    var number = Number(trimmed);
    if (!Number.isFinite(number)) return value;

    var nearestInteger = Math.round(number);
    if (Math.abs(number - nearestInteger) < 1e-9) {
      return String(nearestInteger);
    }

    return number.toFixed(2);
  }

  function formatRows(rows) {
    return rows.map(function (row, rowIndex) {
      if (rowIndex === 0) return row;
      return row.map(formatValue);
    });
  }

  function rowsToTsv(rows) {
    return rows.map(function (row) {
      return row.join("\t");
    }).join("\n");
  }

  function buildCell(tag, value) {
    var cell = document.createElement(tag);
    cell.textContent = value;
    return cell;
  }

  function renderTable(container, text) {
    var rows = formatRows(splitTsv(text));
    if (!rows.length) return;
    var formattedText = rowsToTsv(rows);

    var caption = container.getAttribute("data-caption") || "Tabla exportada por MultiQC";
    var actions = document.createElement("div");
    actions.className = "multiqc-table-actions";

    var captionNode = document.createElement("p");
    captionNode.className = "multiqc-table-caption";
    captionNode.textContent = caption;

    var copyButton = document.createElement("button");
    copyButton.className = "multiqc-copy-button";
    copyButton.type = "button";
    copyButton.textContent = "Copiar TSV";
    copyButton.addEventListener("click", function () {
      if (!navigator.clipboard) {
        copyButton.textContent = "Selecciona la tabla para copiar";
        return;
      }
      navigator.clipboard.writeText(formattedText).then(function () {
        copyButton.textContent = "Copiado";
        window.setTimeout(function () {
          copyButton.textContent = "Copiar TSV";
        }, 1600);
      });
    });

    actions.appendChild(captionNode);
    actions.appendChild(copyButton);

    var wrapper = document.createElement("div");
    wrapper.className = "multiqc-copy-table-wrapper";

    var table = document.createElement("table");
    table.className = "multiqc-copy-table";

    var thead = document.createElement("thead");
    var headRow = document.createElement("tr");
    rows[0].forEach(function (value) {
      headRow.appendChild(buildCell("th", value));
    });
    thead.appendChild(headRow);
    table.appendChild(thead);

    var tbody = document.createElement("tbody");
    rows.slice(1).forEach(function (row) {
      var tr = document.createElement("tr");
      row.forEach(function (value) {
        tr.appendChild(buildCell("td", value));
      });
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);

    wrapper.appendChild(table);
    container.replaceChildren(actions, wrapper);
  }

  document.querySelectorAll(".multiqc-table[data-src]").forEach(function (container) {
    var src = container.getAttribute("data-src");
    fetch(src)
      .then(function (response) {
        if (!response.ok) throw new Error(response.status + " " + response.statusText);
        return response.text();
      })
      .then(function (text) {
        renderTable(container, text);
      })
      .catch(function () {
        container.textContent = "No se pudo cargar la tabla MultiQC: " + src;
      });
  });
})();
</script>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dcosimber\.github\.io\/Transcriptomics\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/03_results.html" class="pagination-link" aria-label="RNA Integrity Number (RIN): technical background">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">RNA Integrity Number (RIN): technical background</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/04_alignment_quant.html" class="pagination-link" aria-label="04_alignment_quant.html">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">04_alignment_quant.html</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>