<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Expresión diferencial – HOLOFISHCOLOUR transcriptomics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/06_functional_interpretation.html" rel="next">
<link href="../chapters/04_alignment_quant.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7e34ecb6a0e7991f0346b0751d4a7c3f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/05_differential_expression.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Expresión diferencial</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="index.html" class="sidebar-logo-link">
      <img src="../images/holofishcolour_manhattan_logo_2026.png" alt="HOLOFISHCOLOUR" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../images/holofishcolour_manhattan_logo_2026.png" alt="HOLOFISHCOLOUR" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">HOLOFISHCOLOUR transcriptomics</a>
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container">
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">HOLOFISHCOLOUR transcriptomics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción, antecedentes y objetivos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/02_exp_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Diseño experimental, muestreo y definición de grupos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/03_results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Extracción de ARN, control de calidad molecular y secuenciación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/02_methods_nfcore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Preprocesamiento bioinformático con nf-core/rnaseq</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/03_qc_multiqc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Control de calidad integrado con MultiQC</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/04_alignment_quant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Alineamiento, cuantificación y matrices de expresión</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/05_differential_expression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Expresión diferencial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/06_functional_interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Enriquecimiento funcional e interpretación biológica</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../chapters/07_conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Conclusiones integradas</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container">
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a>
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../appendices/rna_extraction_protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Protocolo de extracción de ARN con TRIzol y columnas Phase Lock Gel Heavy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="../appendices/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Reproducibilidad y decisiones analíticas</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>

  <ul>
  <li><a href="#objetivo-y-criterios-de-lectura" id="toc-objetivo-y-criterios-de-lectura" class="nav-link active" data-scroll-target="#objetivo-y-criterios-de-lectura"><span class="header-section-number">8.1</span> Objetivo y Criterios de Lectura</a></li>
  <li><a href="#diseño-analítico" id="toc-diseño-analítico" class="nav-link" data-scroll-target="#diseño-analítico"><span class="header-section-number">8.2</span> Diseño Analítico</a></li>
  <li><a href="#resumen-integrado-de-contrastes" id="toc-resumen-integrado-de-contrastes" class="nav-link" data-scroll-target="#resumen-integrado-de-contrastes"><span class="header-section-number">8.3</span> Resumen Integrado de Contrastes</a></li>
  <li><a href="#candidatos-agregados" id="toc-candidatos-agregados" class="nav-link" data-scroll-target="#candidatos-agregados"><span class="header-section-number">8.4</span> Candidatos Agregados</a></li>
  <li><a href="#resultados-por-comparación" id="toc-resultados-por-comparación" class="nav-link" data-scroll-target="#resultados-por-comparación"><span class="header-section-number">8.5</span> Resultados por Comparación</a>
  <ul class="collapse">
  <li><a href="#normal-superficie-ocular-oscura-frente-a-superficie-ciega-clara" id="toc-normal-superficie-ocular-oscura-frente-a-superficie-ciega-clara" class="nav-link" data-scroll-target="#normal-superficie-ocular-oscura-frente-a-superficie-ciega-clara"><span class="header-section-number">8.5.1</span> Normal: Superficie Ocular Oscura Frente a Superficie Ciega Clara</a></li>
  <li><a href="#pseudoalbino-superficie-ocular-oscura-frente-a-superficie-ocular-clara" id="toc-pseudoalbino-superficie-ocular-oscura-frente-a-superficie-ocular-clara" class="nav-link" data-scroll-target="#pseudoalbino-superficie-ocular-oscura-frente-a-superficie-ocular-clara"><span class="header-section-number">8.5.2</span> Pseudoalbino: Superficie Ocular Oscura Frente a Superficie Ocular Clara</a></li>
  <li><a href="#pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ciega-clara" id="toc-pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ciega-clara" class="nav-link" data-scroll-target="#pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ciega-clara"><span class="header-section-number">8.5.3</span> Pseudoalbino: Superficie Ciega Oscura Frente a Superficie Ciega Clara</a></li>
  <li><a href="#pseudoalbino-superficie-ocular-clara-frente-a-superficie-ciega-clara" id="toc-pseudoalbino-superficie-ocular-clara-frente-a-superficie-ciega-clara" class="nav-link" data-scroll-target="#pseudoalbino-superficie-ocular-clara-frente-a-superficie-ciega-clara"><span class="header-section-number">8.5.4</span> Pseudoalbino: Superficie Ocular Clara Frente a Superficie Ciega Clara</a></li>
  <li><a href="#pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ocular-oscura" id="toc-pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ocular-oscura" class="nav-link" data-scroll-target="#pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ocular-oscura"><span class="header-section-number">8.5.5</span> Pseudoalbino: Superficie Ciega Oscura Frente a Superficie Ocular Oscura</a></li>
  <li><a href="#pseudoalbino-interacción-superficie-por-pigmentación" id="toc-pseudoalbino-interacción-superficie-por-pigmentación" class="nav-link" data-scroll-target="#pseudoalbino-interacción-superficie-por-pigmentación"><span class="header-section-number">8.5.6</span> Pseudoalbino: Interacción Superficie Por Pigmentación</a></li>
  <li><a href="#pseudoalbino-superficie-ocular-clara-frente-a-normal-superficie-ocular-oscura" id="toc-pseudoalbino-superficie-ocular-clara-frente-a-normal-superficie-ocular-oscura" class="nav-link" data-scroll-target="#pseudoalbino-superficie-ocular-clara-frente-a-normal-superficie-ocular-oscura"><span class="header-section-number">8.5.7</span> Pseudoalbino: Superficie Ocular Clara Frente a Normal: Superficie Ocular Oscura</a></li>
  <li><a href="#pseudoalbino-superficie-ciega-oscura-frente-a-normal-superficie-ciega-clara" id="toc-pseudoalbino-superficie-ciega-oscura-frente-a-normal-superficie-ciega-clara" class="nav-link" data-scroll-target="#pseudoalbino-superficie-ciega-oscura-frente-a-normal-superficie-ciega-clara"><span class="header-section-number">8.5.8</span> Pseudoalbino: Superficie Ciega Oscura Frente a Normal: Superficie Ciega Clara</a></li>
  </ul></li>
  <li><a href="#coherencia-entre-contrastes" id="toc-coherencia-entre-contrastes" class="nav-link" data-scroll-target="#coherencia-entre-contrastes"><span class="header-section-number">8.6</span> Coherencia Entre Contrastes</a></li>
  <li><a href="#análisis-de-síntesis-añadidos" id="toc-análisis-de-síntesis-añadidos" class="nav-link" data-scroll-target="#análisis-de-síntesis-añadidos"><span class="header-section-number">8.7</span> Análisis de Síntesis Añadidos</a></li>
  <li><a href="#puente-hacia-interpretación-funcional" id="toc-puente-hacia-interpretación-funcional" class="nav-link" data-scroll-target="#puente-hacia-interpretación-funcional"><span class="header-section-number">8.8</span> Puente Hacia Interpretación Funcional</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Expresión diferencial</span></h1>
</div>



<div class="quarto-title-meta">




  </div>



</header>


<section id="objetivo-y-criterios-de-lectura" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="objetivo-y-criterios-de-lectura"><span class="header-section-number">8.1</span> Objetivo y Criterios de Lectura</h2>
<p>Este capítulo documenta el bloque de expresión diferencial del proyecto <strong>HOLOFISHCOLOUR</strong>. La pregunta general es si las regiones de piel normal y pseudoalbina de rodaballo mantienen un eje transcriptómico coherente con pigmentación, superficie anatómica y estado tisular, o si el pseudoalbinismo reorganiza esos ejes de forma más compleja.</p>
<p>La lectura se organiza en dos niveles. Primero se presenta una síntesis agregada de todos los contrastes, con el número de genes evaluados, genes diferencialmente expresados y sesgo direccional. Después se desglosan los resultados comparación por comparación, incorporando para cada una el objetivo biológico, el diseño usado, los genes principales, los gráficos diagnósticos y la interpretación. La interpretación funcional detallada de GO, melanogénesis, matriz extracelular, cresta neural, retinoides y estructura tisular se desarrolla en el capítulo siguiente; aquí se conserva el foco en la evidencia diferencial.</p>
<p>El análisis parte de la cuantificación génica generada por <a href="https://combine-lab.github.io/salmon/"><code>Salmon</code></a> <span class="citation" data-cites="Patro2017Salmon">[<a href="01_intro.html#ref-Patro2017Salmon" role="doc-biblioref">1</a>]</span> dentro del flujo <code>star_salmon</code> de nf-core/rnaseq. Los modelos se ajustaron con <a href="https://bioconductor.org/packages/release/bioc/html/DESeq2.html"><code>DESeq2</code></a> <span class="citation" data-cites="Love2014DESeq2">[<a href="01_intro.html#ref-Love2014DESeq2" role="doc-biblioref">2</a>]</span>, usando conteos enteros a nivel de gen, filtrado mínimo de expresión y diseños específicos para cada contraste.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lectura de los efectos">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lectura de los efectos
</div>
</div>
<div class="callout-body-container callout-body">
<p>En todas las tablas, un <code>log2FoldChange</code> positivo indica mayor expresión en el <strong>primer grupo</strong> del contraste. En <code>N_OD_vs_N_BL</code>, por ejemplo, un efecto positivo significa mayor expresión en piel normal ocular oscura (<code>N_OD</code>) que en piel normal ciega clara (<code>N_BL</code>). Un efecto negativo significa mayor expresión en el segundo grupo.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Diferencia entre significación y lista interpretativa">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Diferencia entre significación y lista interpretativa
</div>
</div>
<div class="callout-body-container callout-body">
<p>La columna de DEGs resume genes con FDR &lt; 0.05. Las columnas <code>Up</code> y <code>Down</code> se calcularon sobre la lista usada para interpretación, que además exige |log2FC| &gt;= 1. Por eso <code>N_OD_vs_N_BL</code> tiene 218 genes significativos por FDR, pero 188 genes en la lista direccional filtrada por tamaño de efecto.</p>
</div>
</div>
</section>
<section id="diseño-analítico" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="diseño-analítico"><span class="header-section-number">8.2</span> Diseño Analítico</h2>
<p>El bloque inferencial se restringió a <strong>20 muestras de piel</strong>. Las muestras intestinales y el bloque exploratorio PNK/ambicoloration permanecen documentados en el QC global, pero no se mezclaron con los contrastes principales. Esta decisión evita que el análisis diferencial responda a una pregunta demasiado amplia y conserva comparaciones interpretables entre superficie, pigmentación y condición.</p>
<p>El filtrado previo mantuvo genes con al menos <strong>10 conteos en 3 muestras</strong>. Los contrastes pareados incorporaron <code>turbot_id</code> para controlar diferencias basales entre individuos cuando las dos regiones proceden del mismo pez. Los contrastes no pareados frente a piel normal esperada se ajustaron con <code>~ group_code</code>, porque comparan grupos fenotípicos distintos y no todas las muestras comparten individuo.</p>
<div id="tbl-de-contrast-design" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-de-contrast-design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.1: Contrastes diferenciales ajustados con DESeq2 y lectura direccional de cada coeficiente.
</figcaption>
<div aria-describedby="tbl-de-contrast-design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Contraste</th>
<th>Pregunta biológica</th>
<th>Diseño</th>
<th>Lectura del coeficiente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>N_OD_vs_N_BL</code></td>
<td>Normal: superficie ocular oscura frente a superficie ciega clara.</td>
<td><code>~ turbot_id + group_code</code></td>
<td>Positivo: mayor en <code>N_OD</code>; negativo: mayor en <code>N_BL</code>.</td>
</tr>
<tr class="even">
<td><code>P_OD_vs_P_OL</code></td>
<td>Qué cambia dentro de superficie ocular pseudoalbina entre zona oscura y zona clara.</td>
<td><code>~ turbot_id + group_code</code></td>
<td>Positivo: mayor en <code>P_OD</code>; negativo: mayor en <code>P_OL</code>.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_P_BL</code></td>
<td>Qué se asocia a pigmentación ectópica en la superficie ciega pseudoalbina.</td>
<td><code>~ turbot_id + group_code</code></td>
<td>Positivo: mayor en <code>P_BD</code>; negativo: mayor en <code>P_BL</code>.</td>
</tr>
<tr class="even">
<td><code>P_OL_vs_P_BL</code></td>
<td>Si las zonas claras pseudoalbinas son equivalentes entre superficies.</td>
<td><code>~ turbot_id + group_code</code></td>
<td>Positivo: mayor en <code>P_OL</code>; negativo: mayor en <code>P_BL</code>.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_P_OD</code></td>
<td>Si las zonas oscuras pseudoalbinas son equivalentes entre superficies.</td>
<td><code>~ turbot_id + group_code</code></td>
<td>Positivo: mayor en <code>P_BD</code>; negativo: mayor en <code>P_OD</code>.</td>
</tr>
<tr class="even">
<td><code>P_surface_x_pigmentation</code></td>
<td>Pseudoalbino: si el efecto de pigmentación clara/oscura depende de la superficie ocular/ciega.</td>
<td><code>~ turbot_id + surface + pigmentation + surface:pigmentation</code></td>
<td>Positivo: coeficiente de interacción más alto para superficie ciega y pigmentación oscura; negativo: interacción en sentido contrario.</td>
</tr>
<tr class="odd">
<td><code>P_OL_vs_N_OD</code></td>
<td>Cuánto se separa una zona ocular clara anómala del estado ocular oscuro esperado.</td>
<td><code>~ group_code</code></td>
<td>Positivo: mayor en <code>P_OL</code>; negativo: mayor en <code>N_OD</code>.</td>
</tr>
<tr class="even">
<td><code>P_BD_vs_N_BL</code></td>
<td>Cuánto se separa una zona ciega oscura pseudoalbina del estado ciego claro normal.</td>
<td><code>~ group_code</code></td>
<td>Positivo: mayor en <code>P_BD</code>; negativo: mayor en <code>N_BL</code>.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Los contrastes tienen tres papeles complementarios. <code>N_OD_vs_N_BL</code> define la referencia fisiológica. <code>P_OD_vs_P_OL</code> y <code>P_BD_vs_P_BL</code> interrogan el pseudoalbinismo dentro de cada superficie. <code>P_OL_vs_P_BL</code>, <code>P_BD_vs_P_OD</code> y <code>P_surface_x_pigmentation</code> separan efecto de superficie, efecto de color e interacción. Por último, <code>P_OL_vs_N_OD</code> y <code>P_BD_vs_N_BL</code> comparan regiones anómalas con el estado normal esperado para esa superficie.</p>
</section>
<section id="resumen-integrado-de-contrastes" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="resumen-integrado-de-contrastes"><span class="header-section-number">8.3</span> Resumen Integrado de Contrastes</h2>
<p>Los ocho contrastes se completaron correctamente. El número de genes evaluados varió entre <strong>13878</strong> y <strong>15101</strong>, en función del subconjunto de muestras y del filtrado de expresión. <code>P_BD_vs_N_BL</code> fue el contraste con más genes diferencialmente expresados, seguido de <code>N_OD_vs_N_BL</code> y <code>P_OD_vs_P_OL</code>.</p>
<div id="fig-de-summary-counts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-summary-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/05_de/summary/deg_counts_by_contrast.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;8.1: Número de genes diferencialmente expresados por contraste, separados por dirección del efecto."><img src="../figures/05_de/summary/deg_counts_by_contrast.png" class="img-fluid figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-summary-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.1: Número de genes diferencialmente expresados por contraste, separados por dirección del efecto.
</figcaption>
</figure>
</div>
<div id="tbl-de-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-de-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.2: Resumen agregado de expresión diferencial. <code>Up</code> y <code>Down</code> usan FDR &lt; 0.05 y |log2FC| &gt;= 1.
</figcaption>
<div aria-describedby="tbl-de-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Contraste</th>
<th style="text-align: right;">n muestras</th>
<th style="text-align: right;">Genes testados</th>
<th style="text-align: right;">DEGs FDR &lt; 0.05</th>
<th style="text-align: right;">DEGs con efecto</th>
<th style="text-align: right;">Up</th>
<th style="text-align: right;">Down</th>
<th>Lectura rápida</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>N_OD_vs_N_BL</code></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">15084</td>
<td style="text-align: right;">218</td>
<td style="text-align: right;">188</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">52</td>
<td>Normal: superficie ocular oscura frente a superficie ciega clara.</td>
</tr>
<tr class="even">
<td><code>P_OD_vs_P_OL</code></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">14371</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">58</td>
<td>Pseudoalbinismo ocular; mezcla señal de pigmentación con matriz extracelular y remodelado tisular.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_P_BL</code></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">13878</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">63</td>
<td>Pigmentación ectópica en superficie ciega; no reproduce limpiamente el eje melanogénico normal.</td>
</tr>
<tr class="even">
<td><code>P_OL_vs_P_BL</code></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">14468</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">55</td>
<td>Color claro constante; las zonas claras pseudoalbinas retienen identidad de superficie.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_P_OD</code></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">13908</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">0</td>
<td>Color oscuro constante; separación completa hacia <code>P_BD</code>.</td>
</tr>
<tr class="even">
<td><code>P_surface_x_pigmentation</code></td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">15101</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td>Interacción superficie por pigmentación focalizada y no masiva.</td>
</tr>
<tr class="odd">
<td><code>P_OL_vs_N_OD</code></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">15005</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">37</td>
<td>Zona ocular clara anómala frente al estado ocular oscuro esperado.</td>
</tr>
<tr class="even">
<td><code>P_BD_vs_N_BL</code></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">14483</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">68</td>
<td>Pseudoalbino ciego oscuro frente a Normal ciego claro; contraste más intenso del bloque.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La síntesis de <a href="#tbl-de-summary" class="quarto-xref">Tabla&nbsp;<span>8.2</span></a> y <a href="#fig-de-summary-counts" class="quarto-xref">Figura&nbsp;<span>8.1</span></a> deja tres mensajes claros. El eje normal <code>N_OD_vs_N_BL</code> recupera genes de pigmentación y melanocitos, pero también una señal fuerte de matriz extracelular en sentido opuesto. El pseudoalbinismo ocular (<code>P_OD_vs_P_OL</code>) conserva parte de esa organización, aunque con un componente estructural notable. La pigmentación ectópica ciega (<code>P_BD_vs_P_BL</code> y, sobre todo, <code>P_BD_vs_N_BL</code>) es la señal más divergente: produce muchos cambios, pero dominados por estructura tisular, músculo/sarcomero, epidermis e inmunidad más que por una simple activación melanogénica terminal.</p>
</section>
<section id="candidatos-agregados" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="candidatos-agregados"><span class="header-section-number">8.4</span> Candidatos Agregados</h2>
<p>La tabla siguiente no pretende sustituir las listas completas de DEGs. Resume genes que ayudan a leer cada comparación por su significación, tamaño de efecto o coherencia biológica. Los identificadores <code>ENSSMAG</code> sin símbolo no se han eliminado: en un genoma no modelo pueden ser señales reales pendientes de curación funcional.</p>
<div id="tbl-de-candidates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-de-candidates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.3: Genes y ejes interpretativos destacados por contraste. La tabla completa de genes por dirección está disponible como TSV.
</figcaption>
<div aria-describedby="tbl-de-candidates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Contraste</th>
<th>Dirección</th>
<th>Genes representativos</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>N_OD_vs_N_BL</code></td>
<td>Up en <code>N_OD</code></td>
<td><code>tyrp1b</code>, <code>TYRP1</code>, <code>tmem130</code>, <code>slc24a4b</code>, <code>KIF5B</code></td>
<td>Programa pigmentario normal con genes de melanosoma y melanocitos.</td>
</tr>
<tr class="even">
<td><code>N_OD_vs_N_BL</code></td>
<td>Down en <code>N_OD</code></td>
<td><code>thbs4a</code>, <code>c1qtnf5</code>, <code>CPZ</code>, <code>fndc1</code>, <code>abi3bpa</code></td>
<td>Mayor peso de matriz extracelular y adhesión en la superficie ciega clara.</td>
</tr>
<tr class="odd">
<td><code>P_OD_vs_P_OL</code></td>
<td>Up en <code>P_OD</code></td>
<td><code>col10a1a</code>, <code>col5a2b</code>, <code>col10a1b</code>, <code>cilp2</code>, <code>tnn</code></td>
<td>Región ocular oscura pseudoalbina con fuerte componente de matriz y tejido.</td>
</tr>
<tr class="even">
<td><code>P_OD_vs_P_OL</code></td>
<td>Down en <code>P_OD</code></td>
<td><code>dgat2</code>, <code>crabp1a</code>, <code>mmp30</code>, <code>rab15</code></td>
<td>Mayor señal en <code>P_OL</code> de metabolismo lipídico, retinoides y remodelado.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_P_BL</code></td>
<td>Up en <code>P_BD</code></td>
<td><code>dgat2</code>, <code>MLF1</code>, <code>lbx2</code>, <code>pvalb1</code>, <code>lemd1</code></td>
<td>Lista positiva menor, heterogénea, sin eje melanogénico dominante.</td>
</tr>
<tr class="even">
<td><code>P_BD_vs_P_BL</code></td>
<td>Down en <code>P_BD</code></td>
<td><code>mpx</code>, <code>irg1l</code>, <code>anxa3a</code>, varios <code>ENSSMAG</code></td>
<td>La señal diferencial dominante queda más alta en <code>P_BL</code>.</td>
</tr>
<tr class="odd">
<td><code>P_OL_vs_P_BL</code></td>
<td>Up en <code>P_OL</code></td>
<td><code>crabp1a</code>, <code>dgat2</code>, <code>ACVR1C</code>, <code>ttc9b</code>, <code>mab21l2</code></td>
<td>Diferencia de superficie bajo color claro con retinoides/lípidos en <code>P_OL</code>.</td>
</tr>
<tr class="even">
<td><code>P_OL_vs_P_BL</code></td>
<td>Down en <code>P_OL</code></td>
<td><code>col10a1a</code>, <code>col5a2b</code>, <code>col10a1b</code>, <code>spp1</code>, <code>notum2</code></td>
<td>Matriz extracelular y estructura tisular más altas en <code>P_BL</code>.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_P_OD</code></td>
<td>Up en <code>P_BD</code></td>
<td><code>mybpc2a</code>, <code>atp2a1l</code>, <code>casq1a</code>, <code>gatm</code>, <code>TPM1</code></td>
<td>Señal direccional de músculo/sarcomero y metabolismo en ciega oscura.</td>
</tr>
<tr class="even">
<td><code>P_surface_x_pigmentation</code></td>
<td>Interacción positiva</td>
<td><code>crabp1a</code>, <code>dgat2</code>, <code>ACVR1C</code>, <code>rab15</code>, <code>plin2</code></td>
<td>Interacción focal con retinoides, lípidos y señalización.</td>
</tr>
<tr class="odd">
<td><code>P_surface_x_pigmentation</code></td>
<td>Interacción negativa</td>
<td><code>sdk2a</code>, <code>htr2b</code></td>
<td>Adhesión/señalización con efecto no aditivo en sentido opuesto.</td>
</tr>
<tr class="even">
<td><code>P_OL_vs_N_OD</code></td>
<td>Down en <code>P_OL</code></td>
<td>varios <code>ENSSMAG</code>, con <code>N_OD</code> como grupo alto</td>
<td>Pérdida parcial del programa ocular oscuro esperado.</td>
</tr>
<tr class="odd">
<td><code>P_BD_vs_N_BL</code></td>
<td>Up en <code>P_BD</code></td>
<td><code>vcla</code>, <code>usp13</code>, <code>ca2</code>, <code>smyd2b</code>, <code>frmd5a</code></td>
<td>Activación amplia en región ciega oscura anómala.</td>
</tr>
<tr class="even">
<td><code>P_BD_vs_N_BL</code></td>
<td>Down en <code>P_BD</code></td>
<td>varios <code>ENSSMAG</code>, <code>trim25</code></td>
<td>Señal más alta en la superficie ciega clara normal, con componente inmune/epidérmico.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="resultados-por-comparación" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="resultados-por-comparación"><span class="header-section-number">8.5</span> Resultados por Comparación</h2>
<section id="normal-superficie-ocular-oscura-frente-a-superficie-ciega-clara" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="normal-superficie-ocular-oscura-frente-a-superficie-ciega-clara"><span class="header-section-number">8.5.1</span> Normal: Superficie Ocular Oscura Frente a Superficie Ciega Clara</h3>
<p><code>N_OD_vs_N_BL</code> es la referencia fisiológica del estudio. Compara piel ocular oscura normal frente a piel ciega clara normal, controlando el efecto de individuo con <code>~ turbot_id + group_code</code>. Se evaluaron <strong>15084 genes</strong>; <strong>218</strong> fueron significativos por FDR &lt; 0.05 y <strong>188</strong> superaron además |log2FC| &gt;= 1.</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>N_OD_vs_N_BL</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>N_OD</code></td>
<td><code>tyrp1b / ENSSMAG00000012712</code></td>
<td style="text-align: right;">8.39</td>
<td style="text-align: right;">1.93e-23</td>
<td>Marcador de pigmentación, muy alto en piel ocular oscura.</td>
</tr>
<tr class="even">
<td>Up en <code>N_OD</code></td>
<td><code>TYRP1 / ENSSMAG00000010205</code></td>
<td style="text-align: right;">5.29</td>
<td style="text-align: right;">4.03e-08</td>
<td>Melanogénesis y melanosoma, coherente con la referencia normal.</td>
</tr>
<tr class="odd">
<td>Up en <code>N_OD</code></td>
<td><code>slc24a4b / ENSSMAG00000002036</code></td>
<td style="text-align: right;">4.84</td>
<td style="text-align: right;">8.40e-08</td>
<td>Transporte iónico asociado a pigmentación en vertebrados.</td>
</tr>
<tr class="even">
<td>Down en <code>N_OD</code></td>
<td><code>thbs4a / ENSSMAG00000010306</code></td>
<td style="text-align: right;">-1.69</td>
<td style="text-align: right;">7.17e-08</td>
<td>Matriz extracelular más alta en <code>N_BL</code>.</td>
</tr>
<tr class="odd">
<td>Down en <code>N_OD</code></td>
<td><code>c1qtnf5 / ENSSMAG00000016467</code></td>
<td style="text-align: right;">-1.85</td>
<td style="text-align: right;">4.94e-06</td>
<td>Señal estructural/metabólica en piel ciega clara.</td>
</tr>
<tr class="even">
<td>Down en <code>N_OD</code></td>
<td><code>CPZ / ENSSMAG00000009599</code></td>
<td style="text-align: right;">-1.26</td>
<td style="text-align: right;">7.85e-06</td>
<td>Matriz y procesamiento extracelular, mayor en <code>N_BL</code>.</td>
</tr>
</tbody>
</table>
<div id="fig-de-nod-nbl" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-nod-nbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/N_OD_vs_N_BL/volcano_N_OD_vs_N_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Volcano plot del contraste normal ocular oscura frente a normal ciega clara."><img src="../figures/05_de/contrasts/N_OD_vs_N_BL/volcano_N_OD_vs_N_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste normal ocular oscura frente a normal ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/N_OD_vs_N_BL/ma_N_OD_vs_N_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="MA plot del contraste normal ocular oscura frente a normal ciega clara."><img src="../figures/05_de/contrasts/N_OD_vs_N_BL/ma_N_OD_vs_N_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste normal ocular oscura frente a normal ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/N_OD_vs_N_BL/heatmap_N_OD_vs_N_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Heatmap de genes destacados para el contraste normal ocular oscura frente a normal ciega clara."><img src="../figures/05_de/contrasts/N_OD_vs_N_BL/heatmap_N_OD_vs_N_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste normal ocular oscura frente a normal ciega clara.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-nod-nbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.2: Contraste <code>N_OD_vs_N_BL</code>. Los efectos positivos corresponden a piel ocular oscura normal y los negativos a piel ciega clara normal.
</figcaption>
</figure>
</div>
<p>La señal positiva recupera un programa de pigmentación esperado, con genes de melanosoma y diferenciación melanocítica. En paralelo, la señal negativa se enriquece en matriz extracelular, colágeno y adhesión. Esta mezcla es importante: el contraste fisiológico no mide solo color, sino también identidad de superficie y composición tisular.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/N_OD_vs_N_BL_significant_annotated.tsv">DEGs significativos anotados de <code>N_OD_vs_N_BL</code></a>.</p>
</section>
<section id="pseudoalbino-superficie-ocular-oscura-frente-a-superficie-ocular-clara" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="pseudoalbino-superficie-ocular-oscura-frente-a-superficie-ocular-clara"><span class="header-section-number">8.5.2</span> Pseudoalbino: Superficie Ocular Oscura Frente a Superficie Ocular Clara</h3>
<p><code>P_OD_vs_P_OL</code> compara dentro de pseudoalbinos la región ocular oscura frente a la región ocular clara. Es un contraste pareado por individuo y, por tanto, una de las comparaciones más directas para preguntar qué cambia cuando aparece una zona clara anómala dentro de la superficie ocular. Se evaluaron <strong>14371 genes</strong> y se detectaron <strong>156 DEGs</strong>; todos ellos superaron el umbral de |log2FC| &gt;= 1.</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>P_OD_vs_P_OL</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>P_OD</code></td>
<td><code>col10a1a / ENSSMAG00000018410</code></td>
<td style="text-align: right;">5.62</td>
<td style="text-align: right;">1.08e-13</td>
<td>Colágeno, eje fuerte de matriz extracelular.</td>
</tr>
<tr class="even">
<td>Up en <code>P_OD</code></td>
<td><code>col5a2b / ENSSMAG00000011709</code></td>
<td style="text-align: right;">4.41</td>
<td style="text-align: right;">1.50e-12</td>
<td>Matriz y remodelado tisular.</td>
</tr>
<tr class="odd">
<td>Up en <code>P_OD</code></td>
<td><code>col10a1b / ENSSMAG00000018381</code></td>
<td style="text-align: right;">4.55</td>
<td style="text-align: right;">1.22e-09</td>
<td>Refuerza la señal de colágeno.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OD</code></td>
<td><code>dgat2 / ENSSMAG00000001438</code></td>
<td style="text-align: right;">-4.81</td>
<td style="text-align: right;">6.65e-15</td>
<td>Metabolismo lipídico más alto en <code>P_OL</code>.</td>
</tr>
<tr class="odd">
<td>Down en <code>P_OD</code></td>
<td><code>crabp1a / ENSSMAG00000005604</code></td>
<td style="text-align: right;">-3.88</td>
<td style="text-align: right;">4.19e-06</td>
<td>Unión a ácido retinoico, mayor en <code>P_OL</code>.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OD</code></td>
<td><code>mmp30 / ENSSMAG00000025841</code></td>
<td style="text-align: right;">-2.35</td>
<td style="text-align: right;">1.21e-04</td>
<td>Remodelado de matriz, mayor en <code>P_OL</code>.</td>
</tr>
</tbody>
</table>
<div id="fig-de-pod-pol" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-pod-pol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OD_vs_P_OL/volcano_P_OD_vs_P_OL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Volcano plot del contraste pseudoalbino ocular oscura frente a ocular clara."><img src="../figures/05_de/contrasts/P_OD_vs_P_OL/volcano_P_OD_vs_P_OL.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste pseudoalbino ocular oscura frente a ocular clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OD_vs_P_OL/ma_P_OD_vs_P_OL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="MA plot del contraste pseudoalbino ocular oscura frente a ocular clara."><img src="../figures/05_de/contrasts/P_OD_vs_P_OL/ma_P_OD_vs_P_OL.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste pseudoalbino ocular oscura frente a ocular clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OD_vs_P_OL/heatmap_P_OD_vs_P_OL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Heatmap de genes destacados para el contraste pseudoalbino ocular oscura frente a ocular clara."><img src="../figures/05_de/contrasts/P_OD_vs_P_OL/heatmap_P_OD_vs_P_OL.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste pseudoalbino ocular oscura frente a ocular clara.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-pod-pol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.3: Contraste <code>P_OD_vs_P_OL</code>. Los efectos positivos corresponden a regiones oculares oscuras pseudoalbinas; los negativos, a regiones oculares claras pseudoalbinas.
</figcaption>
</figure>
</div>
<p>El resultado no se limita a una caída simple de genes de melanogénesis. La región <code>P_OD</code> muestra una señal fuerte de colágenos y matriz, mientras que <code>P_OL</code> concentra genes como <code>dgat2</code> y <code>crabp1a</code>, vinculados a lípidos y retinoides. Esto sugiere que la pérdida local de pigmentación en la superficie ocular va acompañada de cambios de microambiente o estado tisular.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_OD_vs_P_OL_significant_annotated.tsv">DEGs significativos anotados de <code>P_OD_vs_P_OL</code></a>.</p>
</section>
<section id="pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ciega-clara" class="level3" data-number="8.5.3">
<h3 data-number="8.5.3" class="anchored" data-anchor-id="pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ciega-clara"><span class="header-section-number">8.5.3</span> Pseudoalbino: Superficie Ciega Oscura Frente a Superficie Ciega Clara</h3>
<p><code>P_BD_vs_P_BL</code> compara zonas oscuras y claras dentro de la superficie ciega pseudoalbina. Este contraste es clave porque pregunta si la pigmentación ectópica de la cara ciega activa un programa parecido al eje normal. Se evaluaron <strong>13878 genes</strong> y se detectaron <strong>79 DEGs</strong>, con un sesgo marcado hacia genes más altos en <code>P_BL</code> (<strong>63 Down</strong> frente a <strong>16 Up</strong>).</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>P_BD_vs_P_BL</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>dgat2 / ENSSMAG00000001438</code></td>
<td style="text-align: right;">1.87</td>
<td style="text-align: right;">3.05e-03</td>
<td>Señal lipídica moderada en ciega oscura.</td>
</tr>
<tr class="even">
<td>Up en <code>P_BD</code></td>
<td><code>MLF1 / ENSSMAG00000015219</code></td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">4.18e-03</td>
<td>Cambio positivo, sin lectura pigmentaria directa.</td>
</tr>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>lbx2 / ENSSMAG00000008154</code></td>
<td style="text-align: right;">1.51</td>
<td style="text-align: right;">5.91e-03</td>
<td>Desarrollo/identidad celular, candidato a revisar.</td>
</tr>
<tr class="even">
<td>Down en <code>P_BD</code></td>
<td><code>mpx / ENSSMAG00000020424</code></td>
<td style="text-align: right;">-3.55</td>
<td style="text-align: right;">4.54e-15</td>
<td>Componente inmune/mieloide más alto en <code>P_BL</code>.</td>
</tr>
<tr class="odd">
<td>Down en <code>P_BD</code></td>
<td><code>irg1l / ENSSMAG00000005426</code></td>
<td style="text-align: right;">-4.46</td>
<td style="text-align: right;">4.41e-07</td>
<td>Inmunidad/metabolismo, mayor en <code>P_BL</code>.</td>
</tr>
<tr class="even">
<td>Down en <code>P_BD</code></td>
<td><code>anxa3a / ENSSMAG00000015210</code></td>
<td style="text-align: right;">-3.13</td>
<td style="text-align: right;">1.23e-04</td>
<td>Señal celular/epitelial más alta en <code>P_BL</code>.</td>
</tr>
</tbody>
</table>
<div id="fig-de-pbd-pbl" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-pbd-pbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_P_BL/volcano_P_BD_vs_P_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Volcano plot del contraste pseudoalbino ciega oscura frente a ciega clara."><img src="../figures/05_de/contrasts/P_BD_vs_P_BL/volcano_P_BD_vs_P_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste pseudoalbino ciega oscura frente a ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_P_BL/ma_P_BD_vs_P_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="MA plot del contraste pseudoalbino ciega oscura frente a ciega clara."><img src="../figures/05_de/contrasts/P_BD_vs_P_BL/ma_P_BD_vs_P_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste pseudoalbino ciega oscura frente a ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_P_BL/heatmap_P_BD_vs_P_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Heatmap de genes destacados para el contraste pseudoalbino ciega oscura frente a ciega clara."><img src="../figures/05_de/contrasts/P_BD_vs_P_BL/heatmap_P_BD_vs_P_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste pseudoalbino ciega oscura frente a ciega clara.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-pbd-pbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.4: Contraste <code>P_BD_vs_P_BL</code>. Los efectos positivos corresponden a superficie ciega oscura pseudoalbina; los negativos, a superficie ciega clara pseudoalbina.
</figcaption>
</figure>
</div>
<p>La dirección del contraste es informativa. Si la pigmentación ectópica ciega fuese una copia transcriptómica de la piel ocular oscura normal, esperaríamos una señal positiva clara de melanogénesis. En cambio, la lista filtrada es pequeña y está dominada por genes más altos en <code>P_BL</code>. En el ranking completo aparecen términos de sarcómero y músculo en el lado positivo, mientras que melanosoma y diferenciación melanocítica no aparecen como un bloque positivo dominante. La conclusión prudente es que <code>P_BD</code> representa un estado tisular divergente, no una simple transposición del programa ocular oscuro.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_BD_vs_P_BL_significant_annotated.tsv">DEGs significativos anotados de <code>P_BD_vs_P_BL</code></a>.</p>
</section>
<section id="pseudoalbino-superficie-ocular-clara-frente-a-superficie-ciega-clara" class="level3" data-number="8.5.4">
<h3 data-number="8.5.4" class="anchored" data-anchor-id="pseudoalbino-superficie-ocular-clara-frente-a-superficie-ciega-clara"><span class="header-section-number">8.5.4</span> Pseudoalbino: Superficie Ocular Clara Frente a Superficie Ciega Clara</h3>
<p><code>P_OL_vs_P_BL</code> mantiene constante el fenotipo claro y compara superficie ocular frente a ciega dentro de pseudoalbinos. Se evaluaron <strong>14468 genes</strong> y se detectaron <strong>70 DEGs</strong>. La mayoría (<strong>55</strong>) fueron negativos, es decir, más altos en <code>P_BL</code>.</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>P_OL_vs_P_BL</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>P_OL</code></td>
<td><code>crabp1a / ENSSMAG00000005604</code></td>
<td style="text-align: right;">4.21</td>
<td style="text-align: right;">1.29e-09</td>
<td>Retinoides y desarrollo, mayor en ocular clara.</td>
</tr>
<tr class="even">
<td>Up en <code>P_OL</code></td>
<td><code>dgat2 / ENSSMAG00000001438</code></td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">1.85e-07</td>
<td>Metabolismo lipídico, mayor en ocular clara.</td>
</tr>
<tr class="odd">
<td>Up en <code>P_OL</code></td>
<td><code>ACVR1C / ENSSMAG00000011491</code></td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">3.53e-04</td>
<td>Señalización TGF-beta/activina, candidato regulador.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OL</code></td>
<td><code>col10a1a / ENSSMAG00000018410</code></td>
<td style="text-align: right;">-7.26</td>
<td style="text-align: right;">2.32e-28</td>
<td>Colágeno mucho más alto en ciega clara.</td>
</tr>
<tr class="odd">
<td>Down en <code>P_OL</code></td>
<td><code>col5a2b / ENSSMAG00000011709</code></td>
<td style="text-align: right;">-5.55</td>
<td style="text-align: right;">1.39e-18</td>
<td>Matriz extracelular más alta en ciega clara.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OL</code></td>
<td><code>notum2 / ENSSMAG00000007311</code></td>
<td style="text-align: right;">-3.91</td>
<td style="text-align: right;">1.50e-06</td>
<td>Modulación de Wnt, mayor en ciega clara.</td>
</tr>
</tbody>
</table>
<div id="fig-de-pol-pbl" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-pol-pbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OL_vs_P_BL/volcano_P_OL_vs_P_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Volcano plot del contraste pseudoalbino ocular clara frente a ciega clara."><img src="../figures/05_de/contrasts/P_OL_vs_P_BL/volcano_P_OL_vs_P_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste pseudoalbino ocular clara frente a ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OL_vs_P_BL/ma_P_OL_vs_P_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="MA plot del contraste pseudoalbino ocular clara frente a ciega clara."><img src="../figures/05_de/contrasts/P_OL_vs_P_BL/ma_P_OL_vs_P_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste pseudoalbino ocular clara frente a ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OL_vs_P_BL/heatmap_P_OL_vs_P_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Heatmap de genes destacados para el contraste pseudoalbino ocular clara frente a ciega clara."><img src="../figures/05_de/contrasts/P_OL_vs_P_BL/heatmap_P_OL_vs_P_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste pseudoalbino ocular clara frente a ciega clara.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-pol-pbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.5: Contraste <code>P_OL_vs_P_BL</code>. Los efectos positivos corresponden a superficie ocular clara pseudoalbina; los negativos, a superficie ciega clara pseudoalbina.
</figcaption>
</figure>
</div>
<p>La similitud macroscópica de color no implica equivalencia transcriptómica. <code>P_OL</code> retiene señales de retinoides y lípidos, mientras que <code>P_BL</code> acumula colágenos, matriz y términos de estructura muscular o tisular. Este contraste separa muy bien pigmentación visible de identidad de superficie.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_OL_vs_P_BL_significant_annotated.tsv">DEGs significativos anotados de <code>P_OL_vs_P_BL</code></a>.</p>
</section>
<section id="pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ocular-oscura" class="level3" data-number="8.5.5">
<h3 data-number="8.5.5" class="anchored" data-anchor-id="pseudoalbino-superficie-ciega-oscura-frente-a-superficie-ocular-oscura"><span class="header-section-number">8.5.5</span> Pseudoalbino: Superficie Ciega Oscura Frente a Superficie Ocular Oscura</h3>
<p><code>P_BD_vs_P_OD</code> mantiene constante el color oscuro y compara la superficie ciega frente a la ocular en pseudoalbinos. Se evaluaron <strong>13908 genes</strong> y se detectaron <strong>47 DEGs</strong>, todos positivos. En otras palabras, con el umbral definido no hubo genes más altos en <code>P_OD</code>; la separación viene completa desde <code>P_BD</code>.</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>P_BD_vs_P_OD</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>mybpc2a / ENSSMAG00000008209</code></td>
<td style="text-align: right;">3.36</td>
<td style="text-align: right;">9.70e-05</td>
<td>Proteína sarcomérica, señal muscular.</td>
</tr>
<tr class="even">
<td>Up en <code>P_BD</code></td>
<td><code>atp2a1l / ENSSMAG00000016974</code></td>
<td style="text-align: right;">3.06</td>
<td style="text-align: right;">8.29e-04</td>
<td>Manejo de calcio, músculo/contracción.</td>
</tr>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>casq1a / ENSSMAG00000013960</code></td>
<td style="text-align: right;">2.91</td>
<td style="text-align: right;">8.29e-04</td>
<td>Calcio y músculo estriado.</td>
</tr>
<tr class="even">
<td>Up en <code>P_BD</code></td>
<td><code>gatm / ENSSMAG00000014093</code></td>
<td style="text-align: right;">2.91</td>
<td style="text-align: right;">1.26e-03</td>
<td>Metabolismo energético.</td>
</tr>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>prr33 / ENSSMAG00000006257</code></td>
<td style="text-align: right;">2.55</td>
<td style="text-align: right;">4.11e-03</td>
<td>Gen estructural/candidato sin lectura pigmentaria directa.</td>
</tr>
<tr class="even">
<td>Up en <code>P_BD</code></td>
<td><code>TPM1 / ENSSMAG00000016387</code></td>
<td style="text-align: right;">2.59</td>
<td style="text-align: right;">6.92e-03</td>
<td>Tropomiosina, estructura contráctil.</td>
</tr>
</tbody>
</table>
<div id="fig-de-pbd-pod" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-pbd-pod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_P_OD/volcano_P_BD_vs_P_OD.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Volcano plot del contraste pseudoalbino ciega oscura frente a ocular oscura."><img src="../figures/05_de/contrasts/P_BD_vs_P_OD/volcano_P_BD_vs_P_OD.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste pseudoalbino ciega oscura frente a ocular oscura.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_P_OD/ma_P_BD_vs_P_OD.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="MA plot del contraste pseudoalbino ciega oscura frente a ocular oscura."><img src="../figures/05_de/contrasts/P_BD_vs_P_OD/ma_P_BD_vs_P_OD.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste pseudoalbino ciega oscura frente a ocular oscura.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_P_OD/heatmap_P_BD_vs_P_OD.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Heatmap de genes destacados para el contraste pseudoalbino ciega oscura frente a ocular oscura."><img src="../figures/05_de/contrasts/P_BD_vs_P_OD/heatmap_P_BD_vs_P_OD.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste pseudoalbino ciega oscura frente a ocular oscura.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-pbd-pod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.6: Contraste <code>P_BD_vs_P_OD</code>. Los efectos positivos corresponden a superficie ciega oscura pseudoalbina.
</figcaption>
</figure>
</div>
<p>Este resultado es uno de los argumentos más sólidos contra una interpretación puramente pigmentaria. Aunque ambas regiones son oscuras, la región ciega oscura expresa más genes asociados a músculo, sarcómero, calcio y metabolismo. La señal probablemente refleja composición tisular, estado de la dermis o proximidad a estructuras subyacentes, y debe interpretarse como identidad de superficie dentro de un color compartido.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_BD_vs_P_OD_significant_annotated.tsv">DEGs significativos anotados de <code>P_BD_vs_P_OD</code></a>.</p>
</section>
<section id="pseudoalbino-interacción-superficie-por-pigmentación" class="level3" data-number="8.5.6">
<h3 data-number="8.5.6" class="anchored" data-anchor-id="pseudoalbino-interacción-superficie-por-pigmentación"><span class="header-section-number">8.5.6</span> Pseudoalbino: Interacción Superficie Por Pigmentación</h3>
<p><code>P_surface_x_pigmentation</code> prueba formalmente si el efecto de pigmentación clara/oscura dentro de pseudoalbinos cambia según la superficie ocular/ciega. Es una hipótesis más estricta que los contrastes simples, porque pregunta por efectos no aditivos. Se evaluaron <strong>15101 genes</strong> y se detectaron <strong>8 DEGs</strong>.</p>
<table class="caption-top table">
<caption>Genes representativos del modelo de interacción <code>P_surface_x_pigmentation</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Interacción positiva</td>
<td><code>crabp1a / ENSSMAG00000005604</code></td>
<td style="text-align: right;">6.41</td>
<td style="text-align: right;">2.01e-07</td>
<td>Ácido retinoico; candidato principal de interacción.</td>
</tr>
<tr class="even">
<td>Interacción positiva</td>
<td><code>dgat2 / ENSSMAG00000001438</code></td>
<td style="text-align: right;">6.39</td>
<td style="text-align: right;">7.28e-06</td>
<td>Metabolismo lipídico dependiente de superficie.</td>
</tr>
<tr class="odd">
<td>Interacción positiva</td>
<td><code>ACVR1C / ENSSMAG00000011491</code></td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">1.45e-02</td>
<td>Señalización; efecto no aditivo.</td>
</tr>
<tr class="even">
<td>Interacción positiva</td>
<td><code>plin2 / ENSSMAG00000011239</code></td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">2.54e-02</td>
<td>Gota lipídica y almacenamiento de lípidos.</td>
</tr>
<tr class="odd">
<td>Interacción negativa</td>
<td><code>sdk2a / ENSSMAG00000000976</code></td>
<td style="text-align: right;">-4.68</td>
<td style="text-align: right;">4.76e-02</td>
<td>Adhesión celular, interacción en sentido opuesto.</td>
</tr>
<tr class="even">
<td>Interacción negativa</td>
<td><code>htr2b / ENSSMAG00000001733</code></td>
<td style="text-align: right;">-3.89</td>
<td style="text-align: right;">4.76e-02</td>
<td>Receptor serotoninérgico, candidato de señalización.</td>
</tr>
</tbody>
</table>
<div id="fig-de-interaction" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_surface_x_pigmentation/volcano_P_surface_x_pigmentation.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Volcano plot del modelo de interacción superficie por pigmentación."><img src="../figures/05_de/contrasts/P_surface_x_pigmentation/volcano_P_surface_x_pigmentation.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del modelo de interacción superficie por pigmentación.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_surface_x_pigmentation/ma_P_surface_x_pigmentation.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="MA plot del modelo de interacción superficie por pigmentación."><img src="../figures/05_de/contrasts/P_surface_x_pigmentation/ma_P_surface_x_pigmentation.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del modelo de interacción superficie por pigmentación.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_surface_x_pigmentation/heatmap_P_surface_x_pigmentation.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Heatmap de genes destacados para el modelo de interacción superficie por pigmentación."><img src="../figures/05_de/contrasts/P_surface_x_pigmentation/heatmap_P_surface_x_pigmentation.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el modelo de interacción superficie por pigmentación.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.7: Modelo <code>P_surface_x_pigmentation</code>. Los efectos representan genes cuyo cambio asociado a pigmentación depende de la superficie.
</figcaption>
</figure>
</div>
<p>La lista corta no debilita el resultado; al contrario, indica que la interacción estricta está concentrada en pocos genes. <code>crabp1a</code>, <code>dgat2</code>, <code>ACVR1C</code> y <code>plin2</code> conectan retinoides, lípidos y señalización, un eje biológicamente plausible para modular pigmentación y diferenciación tisular. La señal negativa añade adhesión y señalización serotoninérgica como hipótesis secundaria.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_surface_x_pigmentation_significant_annotated.tsv">DEGs significativos anotados de <code>P_surface_x_pigmentation</code></a>.</p>
</section>
<section id="pseudoalbino-superficie-ocular-clara-frente-a-normal-superficie-ocular-oscura" class="level3" data-number="8.5.7">
<h3 data-number="8.5.7" class="anchored" data-anchor-id="pseudoalbino-superficie-ocular-clara-frente-a-normal-superficie-ocular-oscura"><span class="header-section-number">8.5.7</span> Pseudoalbino: Superficie Ocular Clara Frente a Normal: Superficie Ocular Oscura</h3>
<p><code>P_OL_vs_N_OD</code> compara una zona ocular clara pseudoalbina con el estado ocular oscuro normal esperado. No es un contraste pareado por individuo, por lo que debe leerse como contraste de estado, no como estimación intraindividuo. Se evaluaron <strong>15005 genes</strong> y se detectaron <strong>38 DEGs</strong>. Solo uno fue positivo; los restantes fueron más altos en <code>N_OD</code>.</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>P_OL_vs_N_OD</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>P_OL</code></td>
<td><code>tnfaip6 / ENSSMAG00000012177</code></td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">9.41e-03</td>
<td>Único DEG más alto en superficie ocular clara pseudoalbina.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OL</code></td>
<td><code>ENSSMAG00000036716</code></td>
<td style="text-align: right;">-3.12</td>
<td style="text-align: right;">1.98e-06</td>
<td>Mayor en el estado ocular oscuro normal.</td>
</tr>
<tr class="odd">
<td>Down en <code>P_OL</code></td>
<td><code>ENSSMAG00000015984</code></td>
<td style="text-align: right;">-3.99</td>
<td style="text-align: right;">1.76e-05</td>
<td>Candidato sin anotación local, mayor en <code>N_OD</code>.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OL</code></td>
<td><code>ENSSMAG00000036554</code></td>
<td style="text-align: right;">-4.50</td>
<td style="text-align: right;">2.96e-04</td>
<td>Cambio intenso pendiente de curación.</td>
</tr>
<tr class="odd">
<td>Down en <code>P_OL</code></td>
<td><code>ENSSMAG00000029313</code></td>
<td style="text-align: right;">-3.49</td>
<td style="text-align: right;">2.96e-04</td>
<td>Mayor en el estado esperado normal.</td>
</tr>
<tr class="even">
<td>Down en <code>P_OL</code></td>
<td><code>ENSSMAG00000014583</code></td>
<td style="text-align: right;">-3.67</td>
<td style="text-align: right;">2.02e-03</td>
<td>Mayor en <code>N_OD</code>, anotación funcional pendiente.</td>
</tr>
</tbody>
</table>
<div id="fig-de-pol-nod" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-pol-nod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OL_vs_N_OD/volcano_P_OL_vs_N_OD.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Volcano plot del contraste pseudoalbino ocular clara frente a normal ocular oscura."><img src="../figures/05_de/contrasts/P_OL_vs_N_OD/volcano_P_OL_vs_N_OD.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste pseudoalbino ocular clara frente a normal ocular oscura.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OL_vs_N_OD/ma_P_OL_vs_N_OD.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="MA plot del contraste pseudoalbino ocular clara frente a normal ocular oscura."><img src="../figures/05_de/contrasts/P_OL_vs_N_OD/ma_P_OL_vs_N_OD.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste pseudoalbino ocular clara frente a normal ocular oscura.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_OL_vs_N_OD/heatmap_P_OL_vs_N_OD.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Heatmap de genes destacados para el contraste pseudoalbino ocular clara frente a normal ocular oscura."><img src="../figures/05_de/contrasts/P_OL_vs_N_OD/heatmap_P_OL_vs_N_OD.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste pseudoalbino ocular clara frente a normal ocular oscura.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-pol-nod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.8: Contraste <code>P_OL_vs_N_OD</code>. Los efectos negativos corresponden a genes más altos en piel ocular oscura normal.
</figcaption>
</figure>
</div>
<p>El resultado sugiere pérdida parcial del programa ocular oscuro normal en la zona clara pseudoalbina, pero con una lista moderada. La abundancia de genes sin símbolo entre los cambios más fuertes obliga a mantener una lectura cauta: son señales útiles para priorización, aunque requieren anotación por ortología o dominios antes de construir un relato mecanístico cerrado.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_OL_vs_N_OD_significant_annotated.tsv">DEGs significativos anotados de <code>P_OL_vs_N_OD</code></a>.</p>
</section>
<section id="pseudoalbino-superficie-ciega-oscura-frente-a-normal-superficie-ciega-clara" class="level3" data-number="8.5.8">
<h3 data-number="8.5.8" class="anchored" data-anchor-id="pseudoalbino-superficie-ciega-oscura-frente-a-normal-superficie-ciega-clara"><span class="header-section-number">8.5.8</span> Pseudoalbino: Superficie Ciega Oscura Frente a Normal: Superficie Ciega Clara</h3>
<p><code>P_BD_vs_N_BL</code> compara la región ciega oscura pseudoalbina con la región ciega clara normal esperada. Es el contraste con mayor señal del capítulo: <strong>14483 genes</strong> evaluados y <strong>288 DEGs</strong>, con <strong>220</strong> genes más altos en <code>P_BD</code>.</p>
<table class="caption-top table">
<caption>Genes representativos del contraste <code>P_BD_vs_N_BL</code>.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Dirección</th>
<th>Gen</th>
<th style="text-align: right;">log2FC</th>
<th style="text-align: right;">FDR</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>vcla / ENSSMAG00000005062</code></td>
<td style="text-align: right;">4.08</td>
<td style="text-align: right;">9.39e-06</td>
<td>Vinculina, adhesión/estructura celular.</td>
</tr>
<tr class="even">
<td>Up en <code>P_BD</code></td>
<td><code>usp13 / ENSSMAG00000003050</code></td>
<td style="text-align: right;">3.09</td>
<td style="text-align: right;">1.23e-05</td>
<td>Regulación proteica, mayor en superficie ciega oscura pseudoalbina.</td>
</tr>
<tr class="odd">
<td>Up en <code>P_BD</code></td>
<td><code>ca2 / ENSSMAG00000005625</code></td>
<td style="text-align: right;">3.62</td>
<td style="text-align: right;">3.07e-05</td>
<td>Carbonic anhydrase, metabolismo/tejido.</td>
</tr>
<tr class="even">
<td>Up en <code>P_BD</code></td>
<td><code>smyd2b / ENSSMAG00000013183</code></td>
<td style="text-align: right;">4.34</td>
<td style="text-align: right;">9.98e-05</td>
<td>Regulación epigenética/cromatina, candidato.</td>
</tr>
<tr class="odd">
<td>Down en <code>P_BD</code></td>
<td><code>ENSSMAG00000002702</code></td>
<td style="text-align: right;">-4.35</td>
<td style="text-align: right;">2.48e-17</td>
<td>Mayor en superficie ciega clara normal; candidato sin anotación local.</td>
</tr>
<tr class="even">
<td>Down en <code>P_BD</code></td>
<td><code>trim25 / ENSSMAG00000012664</code></td>
<td style="text-align: right;">-3.65</td>
<td style="text-align: right;">1.70e-03</td>
<td>Inmunidad innata/regulación antiviral, mayor en <code>N_BL</code>.</td>
</tr>
</tbody>
</table>
<div id="fig-de-pbd-nbl" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-pbd-nbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_N_BL/volcano_P_BD_vs_N_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="Volcano plot del contraste pseudoalbino ciega oscura frente a normal ciega clara."><img src="../figures/05_de/contrasts/P_BD_vs_N_BL/volcano_P_BD_vs_N_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Volcano plot del contraste pseudoalbino ciega oscura frente a normal ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_N_BL/ma_P_BD_vs_N_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="MA plot del contraste pseudoalbino ciega oscura frente a normal ciega clara."><img src="../figures/05_de/contrasts/P_BD_vs_N_BL/ma_P_BD_vs_N_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>MA plot del contraste pseudoalbino ciega oscura frente a normal ciega clara.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/contrasts/P_BD_vs_N_BL/heatmap_P_BD_vs_N_BL.png" class="lightbox" data-gallery="quarto-lightbox-gallery-25" title="Heatmap de genes destacados para el contraste pseudoalbino ciega oscura frente a normal ciega clara."><img src="../figures/05_de/contrasts/P_BD_vs_N_BL/heatmap_P_BD_vs_N_BL.png" class="img-fluid figure-img"></a></p>
<figcaption>Heatmap de genes destacados para el contraste pseudoalbino ciega oscura frente a normal ciega clara.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-pbd-nbl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.9: Contraste <code>P_BD_vs_N_BL</code>. Los efectos positivos corresponden a superficie ciega oscura pseudoalbina y los negativos a superficie ciega clara normal.
</figcaption>
</figure>
</div>
<p>La magnitud del contraste indica que la pigmentación ectópica ciega no es un cambio superficial menor. El enriquecimiento positivo está dominado por Z disc, sarcómero, contracción muscular y estructura celular. En sentido negativo aparecen epidermis, inmunidad y lisosoma. Esta comparación debe leerse como un estado tisular anómalo amplio, no como una simple ganancia de melanina sobre un fondo normal.</p>
<p>Archivo principal: <a href="../tables/05_de/by_contrast/P_BD_vs_N_BL_significant_annotated.tsv">DEGs significativos anotados de <code>P_BD_vs_N_BL</code></a>.</p>
</section>
</section>
<section id="coherencia-entre-contrastes" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="coherencia-entre-contrastes"><span class="header-section-number">8.6</span> Coherencia Entre Contrastes</h2>
<p>Los solapamientos y correlaciones confirman que los ejes no son intercambiables. La correlación entre el eje normal <code>N_OD_vs_N_BL</code> y el eje ocular pseudoalbino <code>P_OD_vs_P_OL</code> es positiva pero baja, mientras que la comparación del eje normal con <code>P_BD_vs_P_BL</code> es negativa. El pseudoalbinismo ocular conserva parte del programa normal; la pigmentación ciega ectópica se separa mucho más.</p>
<div id="tbl-de-correlations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-de-correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.4: Correlaciones de efecto génico entre contrastes relacionados. Se calcularon sobre genes comparables, no solo DEGs filtrados.
</figcaption>
<div aria-describedby="tbl-de-correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Comparación</th>
<th style="text-align: right;">Pearson</th>
<th style="text-align: right;">Spearman</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normal frente a Pseudoalbino en superficie ocular oscura/clara</td>
<td style="text-align: right;">0.221</td>
<td style="text-align: right;">0.162</td>
<td>Conservación parcial, insuficiente para hablar de programa idéntico.</td>
</tr>
<tr class="even">
<td>Normal frente a Pseudoalbino en superficie ciega oscura/clara</td>
<td style="text-align: right;">-0.141</td>
<td style="text-align: right;">-0.102</td>
<td>Divergencia clara del eje ciego ectópico.</td>
</tr>
<tr class="odd">
<td>Pseudoalbino ocular frente a Pseudoalbino ciego en pigmentación oscura/clara</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.304</td>
<td>Concordancia moderada-baja entre ejes pseudoalbinos.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-de-directional-overlap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-de-directional-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.5: Solapamientos direccionales entre el eje fisiológico y los ejes pseudoalbinos.
</figcaption>
<div aria-describedby="tbl-de-directional-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Solapamiento direccional</th>
<th style="text-align: right;">Genes compartidos</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Genes altos en pigmentación oscura normal y altos en pigmentación oscura pseudoalbina ocular</td>
<td style="text-align: right;">8</td>
<td>Conservación limitada del programa oscuro.</td>
</tr>
<tr class="even">
<td>Genes altos en pigmentación clara normal y altos en pigmentación clara pseudoalbina ocular</td>
<td style="text-align: right;">3</td>
<td>Conservación baja del estado claro.</td>
</tr>
<tr class="odd">
<td>Genes altos en pigmentación oscura normal y altos en superficie ciega oscura pseudoalbina</td>
<td style="text-align: right;">1</td>
<td>Pigmentación ectópica ciega muy divergente.</td>
</tr>
<tr class="even">
<td>Genes altos en pigmentación clara normal y altos en superficie ciega clara pseudoalbina</td>
<td style="text-align: right;">0</td>
<td>Sin conservación detectable en este cruce.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-de-overlaps" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-overlaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/summary/venn_primary_pigmentation_axis.png" class="lightbox" data-gallery="quarto-lightbox-gallery-26" title="Venn de genes diferencialmente expresados en el eje principal de pigmentación."><img src="../figures/05_de/summary/venn_primary_pigmentation_axis.png" class="img-fluid figure-img"></a></p>
<figcaption>Venn de genes diferencialmente expresados en el eje principal de pigmentación.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="../figures/05_de/summary/upset_all_main_noninteraction.png" class="lightbox" data-gallery="quarto-lightbox-gallery-27" title="UpSet de solapamientos entre contrastes principales no interactivos."><img src="../figures/05_de/summary/upset_all_main_noninteraction.png" class="img-fluid figure-img"></a></p>
<figcaption>UpSet de solapamientos entre contrastes principales no interactivos.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-overlaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.10: Solapamientos entre contrastes principales. La señal compartida existe, pero es limitada, especialmente cuando se compara el eje normal con pigmentación ectópica ciega.
</figcaption>
</figure>
</div>
<div id="fig-de-upset-pseudo" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-de-upset-pseudo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/05_de/summary/upset_pseudoalbino_within_and_surface.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="Figura&nbsp;8.11: Solapamientos entre contrastes pseudoalbinos dentro de superficie y modelo de interacción."><img src="../figures/05_de/summary/upset_pseudoalbino_within_and_surface.png" class="img-fluid figure-img" style="width:90.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-de-upset-pseudo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.11: Solapamientos entre contrastes pseudoalbinos dentro de superficie y modelo de interacción.
</figcaption>
</figure>
</div>
<p>La lectura integrada es que el pseudoalbinismo no puede describirse como una inversión simple entre pigmentación oscura y clara. La región ocular clara pseudoalbina parece perder parte del estado ocular oscuro normal. La región ciega oscura pseudoalbina, en cambio, se comporta como un estado más profundo de reorganización tisular, con fuerte contribución de estructura y composición celular.</p>
</section>
<section id="análisis-de-síntesis-añadidos" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="análisis-de-síntesis-añadidos"><span class="header-section-number">8.7</span> Análisis de Síntesis Añadidos</h2>
<p>Para reforzar este capítulo se añadieron tablas derivadas reproducibles a partir de los resultados ya generados, sin relanzar los modelos DESeq2. El script <a href="../scripts/prepare_de_chapter_tables.R"><code>scripts/prepare_de_chapter_tables.R</code></a> crea:</p>
<ul>
<li>un resumen agregado de contrastes con DEGs por FDR, DEGs con umbral de tamaño de efecto y sesgo direccional;</li>
<li>TSV separados por contraste con los DEGs significativos anotados;</li>
<li>una tabla de genes destacados por contraste y dirección;</li>
<li>una tabla resumida de términos GO por contraste para enlazar este capítulo con la interpretación funcional.</li>
</ul>
<p>Estos archivos quedan incorporados como recursos descargables del libro:</p>
<ul>
<li><a href="../tables/05_de/chapter_summaries/chapter_contrast_summary.tsv">Resumen del capítulo por contraste</a></li>
<li><a href="../tables/05_de/chapter_summaries/chapter_top_genes_by_contrast_direction.tsv">Genes destacados por contraste y dirección</a></li>
<li><a href="../tables/05_de/chapter_summaries/chapter_top_genes_compact.tsv">Genes destacados compactos</a></li>
<li><a href="../tables/05_de/chapter_summaries/chapter_go_terms_by_contrast.tsv">Términos GO resumidos por contraste</a></li>
<li><a href="../tables/05_de/chapter_summaries/chapter_contrast_inventory.tsv">Inventario de figuras y tablas por contraste</a></li>
<li><a href="../tables/05_de/deg_significant_all_contrasts_annotated.tsv">Todos los DEGs significativos anotados</a></li>
<li><a href="../tables/05_de/deg_top50_by_contrast_annotated.tsv">Top 50 genes anotados por contraste</a></li>
<li><a href="../tables/05_de/gene_effect_correlations.tsv">Correlaciones de efecto génico</a></li>
<li><a href="../tables/05_de/deg_directional_overlaps.tsv">Solapamientos direccionales</a></li>
</ul>
</section>
<section id="puente-hacia-interpretación-funcional" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="puente-hacia-interpretación-funcional"><span class="header-section-number">8.8</span> Puente Hacia Interpretación Funcional</h2>
<p>La expresión diferencial establece la arquitectura estadística del resultado. <code>N_OD_vs_N_BL</code> define un eje normal con pigmentación y matriz; <code>P_OD_vs_P_OL</code> conserva parte de esa estructura pero introduce lípidos, retinoides y remodelado; <code>P_BD_vs_P_BL</code> y <code>P_BD_vs_N_BL</code> muestran que la pigmentación ectópica ciega es mucho más divergente. El capítulo siguiente usa esta base para interpretar términos GO, categorías funcionales dirigidas y procesos biológicos en un marco más mecanístico.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Muestras a vigilar al interpretar DE">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Muestras a vigilar al interpretar DE
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las muestras <code>P43</code>, <code>P44</code>, <code>P47</code> y <code>P49</code> mostraron señales técnicas moderadas en QC, principalmente duplicación elevada o menor complejidad. No fueron excluidas porque no mostraron fallo global, pero conviene evitar conclusiones que dependan de una sola muestra, especialmente en contrastes pseudoalbinos con n reducido.</p>
</div>
</div>
</section>
<section id="referencias" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Patro2017Salmon" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">Patro R., Duggal G., Love M. I., Irizarry R. A., Kingsford C. <span>Salmon provides fast and bias-aware quantification of transcript expression</span>. Nature Methods; 2017; 14(4):417-419. doi:<a href="https://doi.org/10.1038/nmeth.4197">10.1038/nmeth.4197</a> <a href="https://doi.org/10.1038/nmeth.4197">https://doi.org/10.1038/nmeth.4197</a></div>
</div>
<div id="ref-Love2014DESeq2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">Love M. I., Huber W., Anders S. <span>Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2</span>. Genome Biology; 2014; 15(12):550. doi:<a href="https://doi.org/10.1186/s13059-014-0550-8">10.1186/s13059-014-0550-8</a> <a href="https://doi.org/10.1186/s13059-014-0550-8">https://doi.org/10.1186/s13059-014-0550-8</a></div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dcosimber\.github\.io\/Transcriptomics\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/04_alignment_quant.html" class="pagination-link" aria-label="Alineamiento, cuantificación y matrices de expresión">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Alineamiento, cuantificación y matrices de expresión</span></span>
      </a>
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/06_functional_interpretation.html" class="pagination-link" aria-label="Enriquecimiento funcional e interpretación biológica">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Enriquecimiento funcional e interpretación biológica</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      }
    });

    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });

  };

})();
          </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>